/**
 * Les icônes des badges — Material Icons, en contour, dessinées par
 * react-icons/md.
 *
 * PAS DE WEBFONT. La maquette du catalogue pose les glyphes avec la police
 * « Material Symbols Rounded » de Google ; le site, lui, dessine ses Material
 * Symbols en SVG inline partout ailleurs (components/anime/v2/RelationsGraph.tsx,
 * components/watch/primary/LangPreferenceModal.tsx) parce qu'« aller chercher la
 * police d'icônes pour six glyphes coûterait une webfont sur une vue que la
 * plupart des visiteurs n'ouvrent jamais ». La même raison vaut ici, en plus
 * fort : la notification d'achievement peut surgir sur n'importe quelle page, et
 * elle ne peut pas attendre le chargement d'une police pour montrer son jeton.
 *
 * react-icons est DÉJÀ une dépendance du projet et porte les 4341 Material
 * Icons avec leur géométrie exacte. On y prend les variantes `MdOutline*`,
 * parce que le catalogue demande des icônes « en contour ».
 *
 * FICHIER GÉNÉRÉ — ne pas éditer à la main. La table de correspondance vit dans
 * tools/badges/gen-icons.mjs, qui vérifie l'existence de chaque composant avant
 * d'écrire. Trois glyphes de la maquette n'existent pas dans le jeu Material
 * Icons et sont remplacés : `skull` -> `dangerous`, `neurology` ->
 * `psychology_alt`, `event_upcoming` -> `upcoming`.
 */

import type { IconType } from "react-icons";
import {
  MdOutlineAccountCircle,
  MdOutlineAlarm,
  MdOutlineAlbum,
  MdOutlineAllInclusive,
  MdOutlineAutoAwesome,
  MdOutlineAutoFixHigh,
  MdOutlineAutorenew,
  MdOutlineAvTimer,
  MdOutlineBedtime,
  MdOutlineBlock,
  MdOutlineBlurOn,
  MdOutlineBolt,
  MdOutlineBookmark,
  MdOutlineBookmarkAdded,
  MdOutlineBrokenImage,
  MdOutlineBubbleChart,
  MdOutlineCake,
  MdOutlineCalendarMonth,
  MdOutlineCast,
  MdOutlineCastle,
  MdOutlineCategory,
  MdOutlineContentCopy,
  MdOutlineContentCut,
  MdOutlineDangerous,
  MdOutlineDarkMode,
  MdOutlineDateRange,
  MdOutlineDeleteSweep,
  MdOutlineDescription,
  MdOutlineDiamond,
  MdOutlineDirectionsBike,
  MdOutlineDiversity1,
  MdOutlineDiversity3,
  MdOutlineDonutLarge,
  MdOutlineDonutSmall,
  MdOutlineEditNote,
  MdOutlineEmojiEvents,
  MdOutlineEmojiFoodBeverage,
  MdOutlineEvent,
  MdOutlineEventAvailable,
  MdOutlineExplore,
  MdOutlineFavorite,
  MdOutlineFavoriteBorder,
  MdOutlineFitnessCenter,
  MdOutlineFlag,
  MdOutlineFormatListNumbered,
  MdOutlineGamepad,
  MdOutlineGavel,
  MdOutlineGridView,
  MdOutlineGroups,
  MdOutlineHistory,
  MdOutlineHistoryEdu,
  MdOutlineHourglassTop,
  MdOutlineLayers,
  MdOutlineLightMode,
  MdOutlineLightbulb,
  MdOutlineLink,
  MdOutlineLocalCafe,
  MdOutlineLocalFireDepartment,
  MdOutlineLocalFlorist,
  MdOutlineLocalMovies,
  MdOutlineLooks3,
  MdOutlineManageSearch,
  MdOutlineMasks,
  MdOutlineMenuBook,
  MdOutlineMic,
  MdOutlineMilitaryTech,
  MdOutlineMood,
  MdOutlineMoodBad,
  MdOutlineMotionPhotosOn,
  MdOutlineMovie,
  MdOutlineMovieFilter,
  MdOutlineMusicNote,
  MdOutlineMyLocation,
  MdOutlinePaid,
  MdOutlinePets,
  MdOutlinePhishing,
  MdOutlinePlayCircle,
  MdOutlinePlaylistAdd,
  MdOutlinePodcasts,
  MdOutlinePrecisionManufacturing,
  MdOutlinePsychology,
  MdOutlinePsychologyAlt,
  MdOutlinePublishedWithChanges,
  MdOutlinePushPin,
  MdOutlineQuestionMark,
  MdOutlineQueueMusic,
  MdOutlineRamenDining,
  MdOutlineRepeatOn,
  MdOutlineReplay,
  MdOutlineRestaurant,
  MdOutlineRestore,
  MdOutlineReviews,
  MdOutlineRocketLaunch,
  MdOutlineSchedule,
  MdOutlineSchool,
  MdOutlineSearch,
  MdOutlineSell,
  MdOutlineSentimentVeryDissatisfied,
  MdOutlineSentimentVerySatisfied,
  MdOutlineSettings,
  MdOutlineShieldMoon,
  MdOutlineShuffle,
  MdOutlineSkipNext,
  MdOutlineSmartDisplay,
  MdOutlineSmartToy,
  MdOutlineSortByAlpha,
  MdOutlineSoupKitchen,
  MdOutlineSpeed,
  MdOutlineSportsBasketball,
  MdOutlineSportsKabaddi,
  MdOutlineSportsMma,
  MdOutlineSportsSoccer,
  MdOutlineSportsVolleyball,
  MdOutlineStyle,
  MdOutlineSubscriptions,
  MdOutlineSummarize,
  MdOutlineSwapVert,
  MdOutlineTempleBuddhist,
  MdOutlineTerminal,
  MdOutlineTextFields,
  MdOutlineTheaterComedy,
  MdOutlineTheaters,
  MdOutlineTimelapse,
  MdOutlineTimeline,
  MdOutlineTimer,
  MdOutlineToday,
  MdOutlineTranslate,
  MdOutlineTravelExplore,
  MdOutlineUpcoming,
  MdOutlineVerifiedUser,
  MdOutlineVideoLibrary,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineWatchLater,
  MdOutlineWbTwilight,
  MdOutlineWeekend,
  MdOutlineWorkspacePremium,
} from "react-icons/md";

export const BADGE_ICONS: Record<string, IconType> = {
  screen1: MdOutlinePlayCircle,
  screen2: MdOutlineVideoLibrary,
  screen3: MdOutlineSubscriptions,
  screenPlus: MdOutlineSmartDisplay,
  screenTwin: MdOutlineGroups,
  screenBroken: MdOutlineBrokenImage,
  pauseOff: MdOutlineMotionPhotosOn,
  dial: MdOutlineSchedule,
  dialPlain: MdOutlineWatchLater,
  dialTicks: MdOutlineTimer,
  dialMoon: MdOutlineBedtime,
  dialDouble: MdOutlineAvTimer,
  hourglass: MdOutlineHourglassTop,
  weekend: MdOutlineWeekend,
  question: MdOutlineQuestionMark,
  copyLink: MdOutlineContentCopy,
  gear: MdOutlineSettings,
  resume: MdOutlinePlayCircle,
  spotlight: MdOutlineLightbulb,
  curious: MdOutlineManageSearch,
  skullNight: MdOutlineDangerous,
  fishHook: MdOutlinePhishing,
  partnerHeart: MdOutlineFavoriteBorder,
  knightPiece: MdOutlinePsychologyAlt,
  history: MdOutlineHistory,
  again3: MdOutlinePublishedWithChanges,
  cinema: MdOutlineMovie,
  genresAll: MdOutlineCategory,
  noPause: MdOutlineTimelapse,
  burst: MdOutlineBolt,
  cutlery: MdOutlineRestaurant,
  flag: MdOutlineFlag,
  three: MdOutlineLooks3,
  loop3: MdOutlineRepeatOn,
  dayD: MdOutlineEvent,
  theaters: MdOutlineTheaters,
  fish: MdOutlinePhishing,
  fist: MdOutlineSportsMma,
  hearts: MdOutlineDiversity1,
  horror: MdOutlineSentimentVeryDissatisfied,
  reborn: MdOutlineAutorenew,
  laugh: MdOutlineSentimentVerySatisfied,
  volley: MdOutlineSportsVolleyball,
  brainAlt: MdOutlinePsychologyAlt,
  bookmark: MdOutlineBookmark,
  bookmarkCheck: MdOutlineBookmarkAdded,
  layers: MdOutlineLayers,
  calendar: MdOutlineCalendarMonth,
  calendarCheck: MdOutlineEventAvailable,
  calendarHalf: MdOutlineDateRange,
  calendarPlus: MdOutlineUpcoming,
  calendarPlay: MdOutlineToday,
  wheel10: MdOutlineDonutSmall,
  wheelFull: MdOutlineDonutLarge,
  rings: MdOutlineAllInclusive,
  link: MdOutlineLink,
  shieldCheck: MdOutlineVerifiedUser,
  film: MdOutlineDescription,
  dpad: MdOutlineGamepad,
  skipOff: MdOutlineSkipNext,
  starList: MdOutlineReviews,
  loop: MdOutlineReplay,
  shuffle: MdOutlineShuffle,
  clapper: MdOutlineMovieFilter,
  gem: MdOutlineDiamond,
  magnifier: MdOutlineSearch,
  timeline: MdOutlineTimeline,
  broadcast: MdOutlinePodcasts,
  speech: MdOutlineTranslate,
  sword: MdOutlineSportsKabaddi,
  heart: MdOutlineFavorite,
  ghost: MdOutlineMoodBad,
  robot: MdOutlineSmartToy,
  leaf: MdOutlineLocalCafe,
  portal: MdOutlineExplore,
  castle: MdOutlineCastle,
  rocket: MdOutlineRocketLaunch,
  teardrop: MdOutlineTheaterComedy,
  smile: MdOutlineMood,
  ball: MdOutlineSportsSoccer,
  note: MdOutlineMusicNote,
  mic: MdOutlineMic,
  brain: MdOutlinePsychology,
  eye: MdOutlineVisibility,
  wand: MdOutlineAutoFixHigh,
  torii: MdOutlineTempleBuddhist,
  school: MdOutlineSchool,
  mask: MdOutlineMasks,
  chef: MdOutlineRamenDining,
  moon: MdOutlineDarkMode,
  sun: MdOutlineLightMode,
  flame: MdOutlineLocalFireDepartment,
  hexCluster: MdOutlineWorkspacePremium,
  gridFull: MdOutlineGridView,
  cake: MdOutlineCake,
  listPlus: MdOutlinePlaylistAdd,
  trophy: MdOutlineEmojiEvents,
  movies: MdOutlineLocalMovies,
  queueMusic: MdOutlineQueueMusic,
  speed: MdOutlineSpeed,
  twilight: MdOutlineWbTwilight,
  recap: MdOutlineSummarize,
  translate: MdOutlineTranslate,
  oldest: MdOutlineRestore,
  selfie: MdOutlineAccountCircle,
  showcase: MdOutlinePushPin,
  console: MdOutlineTerminal,
  gavel: MdOutlineGavel,
  loupeSelf: MdOutlineManageSearch,
  noEntry: MdOutlineBlock,
  players: MdOutlineCast,
  tagsAll: MdOutlineSell,
  longTitle: MdOutlineTextFields,
  compass: MdOutlineExplore,
  ninja: MdOutlineVisibilityOff,
  aura: MdOutlineBolt,
  wall: MdOutlineShieldMoon,
  blade: MdOutlineContentCut,
  sleuth: MdOutlineTravelExplore,
  crown: MdOutlineMilitaryTech,
  scroll: MdOutlineHistoryEdu,
  skull: MdOutlineDangerous,
  pen: MdOutlineEditNote,
  gearHeart: MdOutlineFavoriteBorder,
  spiral: MdOutlineBlurOn,
  card: MdOutlineStyle,
  hoop: MdOutlineSportsBasketball,
  bike: MdOutlineDirectionsBike,
  pot: MdOutlineSoupKitchen,
  titan: MdOutlineFitnessCenter,
  spell: MdOutlineAutoAwesome,
  slime: MdOutlineBubbleChart,
  guild: MdOutlineDiversity3,
  gun: MdOutlineMyLocation,
  mechaG: MdOutlinePrecisionManufacturing,
  space: MdOutlineRocketLaunch,
  bounty: MdOutlinePaid,
  tape: MdOutlineAlbum,
  chain: MdOutlineLink,
  diary: MdOutlineMenuBook,
  teapot: MdOutlineEmojiFoodBeverage,
  cat: MdOutlinePets,
  sunflower: MdOutlineLocalFlorist,
  clockRed: MdOutlineAlarm,
  dropSweep: MdOutlineDeleteSweep,
  swap: MdOutlineSwapVert,
  longSeries: MdOutlineFormatListNumbered,
  alphabet: MdOutlineSortByAlpha,
};

/** L'icône d'un badge, ou le trophée par défaut si la clé est inconnue. */
export function iconFor(key: string): IconType {
  return BADGE_ICONS[key] ?? BADGE_ICONS.trophy;
}

/** Le point d'interrogation des badges secrets non débloqués. */
export const SECRET_ICON: IconType = BADGE_ICONS.question;
