// Real anime emoji "stickers" for the Watch 2gether chat — character art served
// from our own /public so there's no CORS / hotlink / 404 risk from third-party
// hosts.
//
// Images live in  public/emojis/anime/  (sourced from 13 emojigg packs). To add
// more: drop a PNG/WEBP/GIF there and append an entry below with a UNIQUE
// `:shortcode:` (letters/digits/_ only — NO hyphens, the chat regex rejects them)
// and the matching `src`.
//
// Kept SEPARATE from the unicode-backed ANIME_EMOJIS (animeEmojis.ts): stickers
// are image-only, so they MUST stay as `:shortcode:` in the message text (they
// are EXCLUDED from replaceShortcodes) and render as <img> in chat + the
// contentEditable composer.

export interface AnimeSticker {
  /** Shortcode used in chat text, e.g. ":saitama:". Unique across this list AND
   *  ANIME_EMOJIS. Letters/digits/underscore only. */
  shortcode: string;
  /** Human label shown in the picker tooltip / search. */
  label: string;
  /** Image path under /public (served from our own origin). */
  src: string;
  /** Optional search tags for the picker. */
  tags?: string[];
}

export const ANIME_STICKERS: AnimeSticker[] = [
  { shortcode: ":2991_sodakface:", label: "Sodakface", src: "/emojis/anime/2991_sodakface.png", tags: ["sodakface"] },
  { shortcode: ":4912_saitama_shocked:", label: "Saitama Shocked", src: "/emojis/anime/4912_saitama_shocked.png", tags: ["saitama", "shocked"] },
  { shortcode: ":5471_clevelanddeal:", label: "Clevelanddeal", src: "/emojis/anime/5471_clevelanddeal.png", tags: ["clevelanddeal"] },
  { shortcode: ":6734_albedotalk:", label: "Albedotalk", src: "/emojis/anime/6734_albedotalk.gif", tags: ["albedotalk"] },
  { shortcode: ":6768_laffeydrink:", label: "Laffeydrink", src: "/emojis/anime/6768_laffeydrink.png", tags: ["laffeydrink"] },
  { shortcode: ":7266_warspitestudy:", label: "Warspitestudy", src: "/emojis/anime/7266_warspitestudy.png", tags: ["warspitestudy"] },
  { shortcode: ":9215_washinom:", label: "Washinom", src: "/emojis/anime/9215_washinom.png", tags: ["washinom"] },
  { shortcode: ":95_crythumbsup:", label: "Crythumbsup", src: "/emojis/anime/95_crythumbsup.png", tags: ["crythumbsup"] },
  { shortcode: ":aira_gunpoint:", label: "Aira Gunpoint", src: "/emojis/anime/aira_gunpoint.png", tags: ["aira", "gunpoint"] },
  { shortcode: ":akutagawa_stare:", label: "Akutagawa Stare", src: "/emojis/anime/akutagawa_stare.png", tags: ["akutagawa", "stare"] },
  { shortcode: ":albedo_hm:", label: "Albedo Hm", src: "/emojis/anime/albedo_hm.png", tags: ["albedo", "hm"] },
  { shortcode: ":albedofawn:", label: "Albedofawn", src: "/emojis/anime/albedofawn.gif", tags: ["albedofawn"] },
  { shortcode: ":albedohmm:", label: "Albedohmm", src: "/emojis/anime/albedohmm.png", tags: ["albedohmm"] },
  { shortcode: ":albedomoan:", label: "Albedomoan", src: "/emojis/anime/albedomoan.png", tags: ["albedomoan"] },
  { shortcode: ":angry:", label: "Angry", src: "/emojis/anime/angry.gif", tags: ["angry"] },
  { shortcode: ":angry_frieren:", label: "Angry Frieren", src: "/emojis/anime/angry_frieren.png", tags: ["angry", "frieren"] },
  { shortcode: ":angrypaimon:", label: "Angrypaimon", src: "/emojis/anime/angrypaimon.gif", tags: ["angrypaimon"] },
  { shortcode: ":angryrem:", label: "Angryrem", src: "/emojis/anime/angryrem.png", tags: ["angryrem"] },
  { shortcode: ":anime:", label: "Anime", src: "/emojis/anime/anime.png", tags: ["anime"] },
  { shortcode: ":anime_albedoscold:", label: "Anime Albedoscold", src: "/emojis/anime/anime_albedoscold.png", tags: ["anime", "albedoscold"] },
  { shortcode: ":anime_shut_up:", label: "Anime Shut Up", src: "/emojis/anime/anime_shut_up.png", tags: ["anime", "shut", "up"] },
  { shortcode: ":animedance:", label: "Animedance", src: "/emojis/anime/animedance.gif", tags: ["animedance"] },
  { shortcode: ":annoyedgojo:", label: "Annoyedgojo", src: "/emojis/anime/annoyedgojo.gif", tags: ["annoyedgojo"] },
  { shortcode: ":anyadisgust:", label: "Anyadisgust", src: "/emojis/anime/anyadisgust.png", tags: ["anyadisgust"] },
  { shortcode: ":anyagrin:", label: "Anyagrin", src: "/emojis/anime/anyagrin.png", tags: ["anyagrin"] },
  { shortcode: ":anyasly:", label: "Anyasly", src: "/emojis/anime/anyasly.png", tags: ["anyasly"] },
  { shortcode: ":anyaspeechless:", label: "Anyaspeechless", src: "/emojis/anime/anyaspeechless.png", tags: ["anyaspeechless"] },
  { shortcode: ":atomevesip:", label: "Atomevesip", src: "/emojis/anime/atomevesip.png", tags: ["atomevesip"] },
  { shortcode: ":attitiude:", label: "Attitiude", src: "/emojis/anime/attitiude.gif", tags: ["attitiude"] },
  { shortcode: ":aww:", label: "Aww", src: "/emojis/anime/aww.png", tags: ["aww"] },
  { shortcode: ":ayatostare:", label: "Ayatostare", src: "/emojis/anime/ayatostare.png", tags: ["ayatostare"] },
  { shortcode: ":b_sigh:", label: "B Sigh", src: "/emojis/anime/b_sigh.png", tags: ["b", "sigh"] },
  { shortcode: ":belfastdance:", label: "Belfastdance", src: "/emojis/anime/belfastdance.gif", tags: ["belfastdance"] },
  { shortcode: ":bmodancing:", label: "Bmodancing", src: "/emojis/anime/bmodancing.gif", tags: ["bmodancing"] },
  { shortcode: ":bombasticsideeye:", label: "Bombasticsideeye", src: "/emojis/anime/bombasticsideeye.png", tags: ["bombasticsideeye"] },
  { shortcode: ":cat_laughing_at_you:", label: "Cat Laughing At You", src: "/emojis/anime/cat_laughing_at_you.png", tags: ["cat", "laughing", "at", "you"] },
  { shortcode: ":cat_sus:", label: "Cat Sus", src: "/emojis/anime/cat_sus.png", tags: ["cat", "sus"] },
  { shortcode: ":catgirl:", label: "Catgirl", src: "/emojis/anime/catgirl.gif", tags: ["catgirl"] },
  { shortcode: ":catgirl_cozy:", label: "Catgirl Cozy", src: "/emojis/anime/catgirl_cozy.png", tags: ["catgirl", "cozy"] },
  { shortcode: ":catgirlcool:", label: "Catgirlcool", src: "/emojis/anime/catgirlcool.png", tags: ["catgirlcool"] },
  { shortcode: ":catgirlcry:", label: "Catgirlcry", src: "/emojis/anime/catgirlcry.png", tags: ["catgirlcry"] },
  { shortcode: ":catgirlsleep:", label: "Catgirlsleep", src: "/emojis/anime/catgirlsleep.png", tags: ["catgirlsleep"] },
  { shortcode: ":chibi_hutao_love:", label: "Chibi Hutao Love", src: "/emojis/anime/chibi_hutao_love.png", tags: ["chibi", "hutao", "love"] },
  { shortcode: ":chibi_paimon_hesitating:", label: "Chibi Paimon Hesitating", src: "/emojis/anime/chibi_paimon_hesitating.png", tags: ["chibi", "paimon", "hesitating"] },
  { shortcode: ":chibi_paimon_think:", label: "Chibi Paimon Think", src: "/emojis/anime/chibi_paimon_think.png", tags: ["chibi", "paimon", "think"] },
  { shortcode: ":choso_facepalm:", label: "Choso Facepalm", src: "/emojis/anime/choso_facepalm.png", tags: ["choso", "facepalm"] },
  { shortcode: ":choso_sleeping:", label: "Choso Sleeping", src: "/emojis/anime/choso_sleeping.png", tags: ["choso", "sleeping"] },
  { shortcode: ":christmas:", label: "Christmas", src: "/emojis/anime/christmas.png", tags: ["christmas"] },
  { shortcode: ":confused:", label: "Confused", src: "/emojis/anime/confused.png", tags: ["confused"] },
  { shortcode: ":cry_anim:", label: "Cry", src: "/emojis/anime/cry_anim.png", tags: ["cry"] },
  { shortcode: ":dance2:", label: "Dance2", src: "/emojis/anime/dance2.gif", tags: ["dance2"] },
  { shortcode: ":drinking_laffey_pixelated:", label: "Drinking Laffey Pixelated", src: "/emojis/anime/drinking_laffey_pixelated.gif", tags: ["drinking", "laffey", "pixelated"] },
  { shortcode: ":essextuba:", label: "Essextuba", src: "/emojis/anime/essextuba.gif", tags: ["essextuba"] },
  { shortcode: ":eus:", label: "Eus", src: "/emojis/anime/eus.png", tags: ["eus"] },
  { shortcode: ":fight:", label: "Fight", src: "/emojis/anime/fight.png", tags: ["fight"] },
  { shortcode: ":flareon:", label: "Flareon", src: "/emojis/anime/flareon.gif", tags: ["flareon"] },
  { shortcode: ":frierendance:", label: "Frierendance", src: "/emojis/anime/frierendance.gif", tags: ["frierendance"] },
  { shortcode: ":frierenshush:", label: "Frierenshush", src: "/emojis/anime/frierenshush.png", tags: ["frierenshush"] },
  { shortcode: ":frierenspin:", label: "Frierenspin", src: "/emojis/anime/frierenspin.gif", tags: ["frierenspin"] },
  { shortcode: ":gawrgurawavebackgroundless:", label: "Gawrgurawavebackgroundless", src: "/emojis/anime/gawrgurawavebackgroundless.png", tags: ["gawrgurawavebackgroundless"] },
  { shortcode: ":geto_blank:", label: "Geto Blank", src: "/emojis/anime/geto_blank.png", tags: ["geto", "blank"] },
  { shortcode: ":geto_hehe:", label: "Geto Hehe", src: "/emojis/anime/geto_hehe.png", tags: ["geto", "hehe"] },
  { shortcode: ":gifairacross_begone:", label: "Gifairacross Begone", src: "/emojis/anime/gifairacross_begone.gif", tags: ["gifairacross", "begone"] },
  { shortcode: ":gigachad:", label: "Gigachad", src: "/emojis/anime/gigachad.png", tags: ["gigachad"] },
  { shortcode: ":giggle:", label: "Giggle", src: "/emojis/anime/giggle.gif", tags: ["giggle"] },
  { shortcode: ":gir:", label: "Gir", src: "/emojis/anime/gir.gif", tags: ["gir"] },
  { shortcode: ":gojo:", label: "Gojo", src: "/emojis/anime/gojo.gif", tags: ["gojo"] },
  { shortcode: ":gojo_hehe:", label: "Gojo Hehe", src: "/emojis/anime/gojo_hehe.png", tags: ["gojo", "hehe"] },
  { shortcode: ":gojo_wave:", label: "Gojo Wave", src: "/emojis/anime/gojo_wave.png", tags: ["gojo", "wave"] },
  { shortcode: ":gojotwerk:", label: "Gojotwerk", src: "/emojis/anime/gojotwerk.gif", tags: ["gojotwerk"] },
  { shortcode: ":goku:", label: "Goku", src: "/emojis/anime/goku.png", tags: ["goku"] },
  { shortcode: ":gokuthinking:", label: "Gokuthinking", src: "/emojis/anime/gokuthinking.gif", tags: ["gokuthinking"] },
  { shortcode: ":hakari:", label: "Hakari", src: "/emojis/anime/hakari.gif", tags: ["hakari"] },
  { shortcode: ":hamtaroeatsramen:", label: "Hamtaroeatsramen", src: "/emojis/anime/hamtaroeatsramen.gif", tags: ["hamtaroeatsramen"] },
  { shortcode: ":hamtarohappy:", label: "Hamtarohappy", src: "/emojis/anime/hamtarohappy.gif", tags: ["hamtarohappy"] },
  { shortcode: ":hamtarosunflower:", label: "Hamtarosunflower", src: "/emojis/anime/hamtarosunflower.gif", tags: ["hamtarosunflower"] },
  { shortcode: ":hantarodance:", label: "Hantarodance", src: "/emojis/anime/hantarodance.gif", tags: ["hantarodance"] },
  { shortcode: ":happy_frieren:", label: "Happy Frieren", src: "/emojis/anime/happy_frieren.png", tags: ["happy", "frieren"] },
  { shortcode: ":headpat10:", label: "Headpat10", src: "/emojis/anime/headpat10.gif", tags: ["headpat10"] },
  { shortcode: ":headpat14:", label: "Headpat14", src: "/emojis/anime/headpat14.png", tags: ["headpat14"] },
  { shortcode: ":headpat3:", label: "Headpat3", src: "/emojis/anime/headpat3.png", tags: ["headpat3"] },
  { shortcode: ":headpat4:", label: "Headpat4", src: "/emojis/anime/headpat4.png", tags: ["headpat4"] },
  { shortcode: ":herta_kurukuru:", label: "Herta Kurukuru", src: "/emojis/anime/herta_kurukuru.gif", tags: ["herta", "kurukuru"] },
  { shortcode: ":hype:", label: "Hype", src: "/emojis/anime/hype.gif", tags: ["hype"] },
  { shortcode: ":if_confusion:", label: "If Confusion", src: "/emojis/anime/if_confusion.png", tags: ["if", "confusion"] },
  { shortcode: ":im_done:", label: "Im Done", src: "/emojis/anime/im_done.png", tags: ["im", "done"] },
  { shortcode: ":invincible:", label: "Invincible", src: "/emojis/anime/invincible.gif", tags: ["invincible"] },
  { shortcode: ":jam_pochita:", label: "Jam Pochita", src: "/emojis/anime/jam_pochita.gif", tags: ["jam", "pochita"] },
  { shortcode: ":jdjs:", label: "Jdjs", src: "/emojis/anime/jdjs.png", tags: ["jdjs"] },
  { shortcode: ":kakashi_peek:", label: "Kakashi Peek", src: "/emojis/anime/kakashi_peek.png", tags: ["kakashi", "peek"] },
  { shortcode: ":kakashi_scared:", label: "Kakashi Scared", src: "/emojis/anime/kakashi_scared.png", tags: ["kakashi", "scared"] },
  { shortcode: ":kannasip:", label: "Kannasip", src: "/emojis/anime/kannasip.png", tags: ["kannasip"] },
  { shortcode: ":kaorukoblushed:", label: "Kaorukoblushed", src: "/emojis/anime/kaorukoblushed.png", tags: ["kaorukoblushed"] },
  { shortcode: ":kaorukocute:", label: "Kaorukocute", src: "/emojis/anime/kaorukocute.png", tags: ["kaorukocute"] },
  { shortcode: ":kaorukodevilishsmile:", label: "Kaorukodevilishsmile", src: "/emojis/anime/kaorukodevilishsmile.png", tags: ["kaorukodevilishsmile"] },
  { shortcode: ":kaorukodisgust:", label: "Kaorukodisgust", src: "/emojis/anime/kaorukodisgust.png", tags: ["kaorukodisgust"] },
  { shortcode: ":kaorukohappy:", label: "Kaorukohappy", src: "/emojis/anime/kaorukohappy.png", tags: ["kaorukohappy"] },
  { shortcode: ":kaorukoheh:", label: "Kaorukoheh", src: "/emojis/anime/kaorukoheh.png", tags: ["kaorukoheh"] },
  { shortcode: ":kaorukomcdonalds:", label: "Kaorukomcdonalds", src: "/emojis/anime/kaorukomcdonalds.png", tags: ["kaorukomcdonalds"] },
  { shortcode: ":kaorukonom:", label: "Kaorukonom", src: "/emojis/anime/kaorukonom.png", tags: ["kaorukonom"] },
  { shortcode: ":kaorukopout:", label: "Kaorukopout", src: "/emojis/anime/kaorukopout.png", tags: ["kaorukopout"] },
  { shortcode: ":kaorukosleep:", label: "Kaorukosleep", src: "/emojis/anime/kaorukosleep.png", tags: ["kaorukosleep"] },
  { shortcode: ":kaorukoyay:", label: "Kaorukoyay", src: "/emojis/anime/kaorukoyay.png", tags: ["kaorukoyay"] },
  { shortcode: ":karasutabitosybau:", label: "Karasutabitosybau", src: "/emojis/anime/karasutabitosybau.png", tags: ["karasutabitosybau"] },
  { shortcode: ":kekwlaugh:", label: "Kekwlaugh", src: "/emojis/anime/kekwlaugh.gif", tags: ["kekwlaugh"] },
  { shortcode: ":kyoko_thumbsup:", label: "Kyoko Thumbsup", src: "/emojis/anime/kyoko_thumbsup.gif", tags: ["kyoko", "thumbsup"] },
  { shortcode: ":kyokosigh:", label: "Kyokosigh", src: "/emojis/anime/kyokosigh.png", tags: ["kyokosigh"] },
  { shortcode: ":lewdeyes2:", label: "Lewdeyes2", src: "/emojis/anime/lewdeyes2.gif", tags: ["lewdeyes2"] },
  { shortcode: ":listening:", label: "Listening", src: "/emojis/anime/listening.png", tags: ["listening"] },
  { shortcode: ":love_frieren:", label: "Love Frieren", src: "/emojis/anime/love_frieren.png", tags: ["love", "frieren"] },
  { shortcode: ":love_pochita:", label: "Love Pochita", src: "/emojis/anime/love_pochita.gif", tags: ["love", "pochita"] },
  { shortcode: ":luffy10:", label: "Luffy10", src: "/emojis/anime/luffy10.gif", tags: ["luffy10"] },
  { shortcode: ":luffy11:", label: "Luffy11", src: "/emojis/anime/luffy11.gif", tags: ["luffy11"] },
  { shortcode: ":luffy12:", label: "Luffy12", src: "/emojis/anime/luffy12.gif", tags: ["luffy12"] },
  { shortcode: ":luffy13:", label: "Luffy13", src: "/emojis/anime/luffy13.gif", tags: ["luffy13"] },
  { shortcode: ":luffy14:", label: "Luffy14", src: "/emojis/anime/luffy14.gif", tags: ["luffy14"] },
  { shortcode: ":luffy15:", label: "Luffy15", src: "/emojis/anime/luffy15.gif", tags: ["luffy15"] },
  { shortcode: ":luffy16:", label: "Luffy16", src: "/emojis/anime/luffy16.gif", tags: ["luffy16"] },
  { shortcode: ":luffy17:", label: "Luffy17", src: "/emojis/anime/luffy17.gif", tags: ["luffy17"] },
  { shortcode: ":luffy18:", label: "Luffy18", src: "/emojis/anime/luffy18.gif", tags: ["luffy18"] },
  { shortcode: ":luffy19:", label: "Luffy19", src: "/emojis/anime/luffy19.gif", tags: ["luffy19"] },
  { shortcode: ":luffy1:", label: "Luffy1", src: "/emojis/anime/luffy1.gif", tags: ["luffy1"] },
  { shortcode: ":luffy20:", label: "Luffy20", src: "/emojis/anime/luffy20.gif", tags: ["luffy20"] },
  { shortcode: ":luffy21:", label: "Luffy21", src: "/emojis/anime/luffy21.gif", tags: ["luffy21"] },
  { shortcode: ":luffy22:", label: "Luffy22", src: "/emojis/anime/luffy22.gif", tags: ["luffy22"] },
  { shortcode: ":luffy23:", label: "Luffy23", src: "/emojis/anime/luffy23.gif", tags: ["luffy23"] },
  { shortcode: ":luffy24:", label: "Luffy24", src: "/emojis/anime/luffy24.gif", tags: ["luffy24"] },
  { shortcode: ":luffy2:", label: "Luffy2", src: "/emojis/anime/luffy2.gif", tags: ["luffy2"] },
  { shortcode: ":luffy3:", label: "Luffy3", src: "/emojis/anime/luffy3.gif", tags: ["luffy3"] },
  { shortcode: ":luffy4:", label: "Luffy4", src: "/emojis/anime/luffy4.gif", tags: ["luffy4"] },
  { shortcode: ":luffy5:", label: "Luffy5", src: "/emojis/anime/luffy5.gif", tags: ["luffy5"] },
  { shortcode: ":luffy6:", label: "Luffy6", src: "/emojis/anime/luffy6.gif", tags: ["luffy6"] },
  { shortcode: ":luffy7:", label: "Luffy7", src: "/emojis/anime/luffy7.gif", tags: ["luffy7"] },
  { shortcode: ":luffy8:", label: "Luffy8", src: "/emojis/anime/luffy8.gif", tags: ["luffy8"] },
  { shortcode: ":luffy9:", label: "Luffy9", src: "/emojis/anime/luffy9.gif", tags: ["luffy9"] },
  { shortcode: ":luffy:", label: "Luffy", src: "/emojis/anime/luffy.gif", tags: ["luffy"] },
  { shortcode: ":luffy_nose:", label: "Luffy Nose", src: "/emojis/anime/luffy_nose.png", tags: ["luffy", "nose"] },
  { shortcode: ":lunadoro:", label: "Lunadoro", src: "/emojis/anime/lunadoro.png", tags: ["lunadoro"] },
  { shortcode: ":lunch:", label: "Lunch", src: "/emojis/anime/lunch.png", tags: ["lunch"] },
  { shortcode: ":madara:", label: "Madara", src: "/emojis/anime/madara.gif", tags: ["madara"] },
  { shortcode: ":mahito_laugh:", label: "Mahito Laugh", src: "/emojis/anime/mahito_laugh.gif", tags: ["mahito", "laugh"] },
  { shortcode: ":marisacry:", label: "Marisacry", src: "/emojis/anime/marisacry.png", tags: ["marisacry"] },
  { shortcode: ":megumi_blank:", label: "Megumi Blank", src: "/emojis/anime/megumi_blank.png", tags: ["megumi", "blank"] },
  { shortcode: ":megumi_blush:", label: "Megumi Blush", src: "/emojis/anime/megumi_blush.png", tags: ["megumi", "blush"] },
  { shortcode: ":megumi_heart:", label: "Megumi Heart", src: "/emojis/anime/megumi_heart.png", tags: ["megumi", "heart"] },
  { shortcode: ":megumi_pat1:", label: "Megumi Pat1", src: "/emojis/anime/megumi_pat1.gif", tags: ["megumi", "pat1"] },
  { shortcode: ":megumi_pat2:", label: "Megumi Pat2", src: "/emojis/anime/megumi_pat2.gif", tags: ["megumi", "pat2"] },
  { shortcode: ":megumi_wtf:", label: "Megumi Wtf", src: "/emojis/anime/megumi_wtf.png", tags: ["megumi", "wtf"] },
  { shortcode: ":megumitwerk:", label: "Megumitwerk", src: "/emojis/anime/megumitwerk.gif", tags: ["megumitwerk"] },
  { shortcode: ":miku_pout:", label: "Miku Pout", src: "/emojis/anime/miku_pout.png", tags: ["miku", "pout"] },
  { shortcode: ":money_frieren:", label: "Money Frieren", src: "/emojis/anime/money_frieren.png", tags: ["money", "frieren"] },
  { shortcode: ":nanami_happy:", label: "Nanami Happy", src: "/emojis/anime/nanami_happy.png", tags: ["nanami", "happy"] },
  { shortcode: ":narutin:", label: "Narutin", src: "/emojis/anime/narutin.png", tags: ["narutin"] },
  { shortcode: ":naruto:", label: "Naruto", src: "/emojis/anime/naruto.png", tags: ["naruto"] },
  { shortcode: ":naruto_2:", label: "Naruto 2", src: "/emojis/anime/naruto_2.png", tags: ["naruto", "2"] },
  { shortcode: ":naruto_3:", label: "Naruto 3", src: "/emojis/anime/naruto_3.png", tags: ["naruto", "3"] },
  { shortcode: ":naruto_4:", label: "Naruto 4", src: "/emojis/anime/naruto_4.png", tags: ["naruto", "4"] },
  { shortcode: ":naruto_5:", label: "Naruto 5", src: "/emojis/anime/naruto_5.png", tags: ["naruto", "5"] },
  { shortcode: ":naruto_angry:", label: "Naruto Angry", src: "/emojis/anime/naruto_angry.png", tags: ["naruto", "angry"] },
  { shortcode: ":naruto_cool:", label: "Naruto Cool", src: "/emojis/anime/naruto_cool.png", tags: ["naruto", "cool"] },
  { shortcode: ":naruto_hug_panda:", label: "Naruto Hug Panda", src: "/emojis/anime/naruto_hug_panda.png", tags: ["naruto", "hug", "panda"] },
  { shortcode: ":naruto_preparedtofight:", label: "Naruto Preparedtofight", src: "/emojis/anime/naruto_preparedtofight.png", tags: ["naruto", "preparedtofight"] },
  { shortcode: ":naruto_shy:", label: "Naruto Shy", src: "/emojis/anime/naruto_shy.png", tags: ["naruto", "shy"] },
  { shortcode: ":naruto_shy_2:", label: "Naruto Shy 2", src: "/emojis/anime/naruto_shy_2.png", tags: ["naruto", "shy", "2"] },
  { shortcode: ":naruto_uwu:", label: "Naruto Uwu", src: "/emojis/anime/naruto_uwu.png", tags: ["naruto", "uwu"] },
  { shortcode: ":naruto_vsign:", label: "Naruto Vsign", src: "/emojis/anime/naruto_vsign.png", tags: ["naruto", "vsign"] },
  { shortcode: ":naruto_what:", label: "Naruto What", src: "/emojis/anime/naruto_what.png", tags: ["naruto", "what"] },
  { shortcode: ":naruto_what_2:", label: "Naruto What 2", src: "/emojis/anime/naruto_what_2.png", tags: ["naruto", "what", "2"] },
  { shortcode: ":narutotroll:", label: "Narutotroll", src: "/emojis/anime/narutotroll.png", tags: ["narutotroll"] },
  { shortcode: ":narutowhat:", label: "Narutowhat", src: "/emojis/anime/narutowhat.png", tags: ["narutowhat"] },
  { shortcode: ":necoarccry:", label: "Necoarccry", src: "/emojis/anime/necoarccry.png", tags: ["necoarccry"] },
  { shortcode: ":neko:", label: "Neko", src: "/emojis/anime/neko.gif", tags: ["neko"] },
  { shortcode: ":nepsmug:", label: "Nepsmug", src: "/emojis/anime/nepsmug.png", tags: ["nepsmug"] },
  { shortcode: ":nepuwah:", label: "Nepuwah", src: "/emojis/anime/nepuwah.png", tags: ["nepuwah"] },
  { shortcode: ":nobara_sigh:", label: "Nobara Sigh", src: "/emojis/anime/nobara_sigh.gif", tags: ["nobara", "sigh"] },
  { shortcode: ":nod:", label: "Nod", src: "/emojis/anime/nod.gif", tags: ["nod"] },
  { shortcode: ":noireshock:", label: "Noireshock", src: "/emojis/anime/noireshock.png", tags: ["noireshock"] },
  { shortcode: ":nowaying:", label: "Nowaying", src: "/emojis/anime/nowaying.gif", tags: ["nowaying"] },
  { shortcode: ":nyanrainbowdash:", label: "Nyanrainbowdash", src: "/emojis/anime/nyanrainbowdash.gif", tags: ["nyanrainbowdash"] },
  { shortcode: ":obito:", label: "Obito", src: "/emojis/anime/obito.png", tags: ["obito"] },
  { shortcode: ":oceanwaves:", label: "Oceanwaves", src: "/emojis/anime/oceanwaves.gif", tags: ["oceanwaves"] },
  { shortcode: ":omnimandissapointed:", label: "Omnimandissapointed", src: "/emojis/anime/omnimandissapointed.png", tags: ["omnimandissapointed"] },
  { shortcode: ":ookamimiodance:", label: "Ookamimiodance", src: "/emojis/anime/ookamimiodance.gif", tags: ["ookamimiodance"] },
  { shortcode: ":overlord_ainzooalgown1:", label: "Overlord Ainzooalgown1", src: "/emojis/anime/overlord_ainzooalgown1.gif", tags: ["overlord", "ainzooalgown1"] },
  { shortcode: ":overlord_albedo1:", label: "Overlord Albedo1", src: "/emojis/anime/overlord_albedo1.gif", tags: ["overlord", "albedo1"] },
  { shortcode: ":overlord_albedo2:", label: "Overlord Albedo2", src: "/emojis/anime/overlord_albedo2.gif", tags: ["overlord", "albedo2"] },
  { shortcode: ":overlord_mare:", label: "Overlord Mare", src: "/emojis/anime/overlord_mare.gif", tags: ["overlord", "mare"] },
  { shortcode: ":overlord_shalltear:", label: "Overlord Shalltear", src: "/emojis/anime/overlord_shalltear.gif", tags: ["overlord", "shalltear"] },
  { shortcode: ":pat:", label: "Pat", src: "/emojis/anime/pat.png", tags: ["pat"] },
  { shortcode: ":peek:", label: "Peek", src: "/emojis/anime/peek.gif", tags: ["peek"] },
  { shortcode: ":peepowait:", label: "Peepowait", src: "/emojis/anime/peepowait.png", tags: ["peepowait"] },
  { shortcode: ":pensando:", label: "Pensando", src: "/emojis/anime/pensando.png", tags: ["pensando"] },
  { shortcode: ":processando:", label: "Processando", src: "/emojis/anime/processando.gif", tags: ["processando"] },
  { shortcode: ":rarity:", label: "Rarity", src: "/emojis/anime/rarity.gif", tags: ["rarity"] },
  { shortcode: ":rem:", label: "Rem", src: "/emojis/anime/rem.png", tags: ["rem"] },
  { shortcode: ":remilia:", label: "Remilia", src: "/emojis/anime/remilia.png", tags: ["remilia"] },
  { shortcode: ":remm:", label: "Remm", src: "/emojis/anime/remm.gif", tags: ["remm"] },
  { shortcode: ":rezelove:", label: "Rezelove", src: "/emojis/anime/rezelove.png", tags: ["rezelove"] },
  { shortcode: ":rinnesharingan:", label: "Rinnesharingan", src: "/emojis/anime/rinnesharingan.png", tags: ["rinnesharingan"] },
  { shortcode: ":run:", label: "Run", src: "/emojis/anime/run.gif", tags: ["run"] },
  { shortcode: ":sailor_moon_snow_globe:", label: "Sailor Moon Snow Globe", src: "/emojis/anime/sailor_moon_snow_globe.gif", tags: ["sailor", "moon", "snow", "globe"] },
  { shortcode: ":saitama:", label: "Saitama", src: "/emojis/anime/saitama.png", tags: ["saitama"] },
  { shortcode: ":saitamaserious:", label: "Saitamaserious", src: "/emojis/anime/saitamaserious.png", tags: ["saitamaserious"] },
  { shortcode: ":sakugun:", label: "Sakugun", src: "/emojis/anime/sakugun.png", tags: ["sakugun"] },
  { shortcode: ":sakuscared:", label: "Sakuscared", src: "/emojis/anime/sakuscared.png", tags: ["sakuscared"] },
  { shortcode: ":salut:", label: "Salut", src: "/emojis/anime/salut.png", tags: ["salut"] },
  { shortcode: ":sanji_inlove:", label: "Sanji Inlove", src: "/emojis/anime/sanji_inlove.gif", tags: ["sanji", "inlove"] },
  { shortcode: ":sanriomug:", label: "Sanriomug", src: "/emojis/anime/sanriomug.gif", tags: ["sanriomug"] },
  { shortcode: ":scared:", label: "Scared", src: "/emojis/anime/scared.gif", tags: ["scared"] },
  { shortcode: ":sharingane:", label: "Sharingane", src: "/emojis/anime/sharingane.gif", tags: ["sharingane"] },
  { shortcode: ":shinanosleep:", label: "Shinanosleep", src: "/emojis/anime/shinanosleep.png", tags: ["shinanosleep"] },
  { shortcode: ":sip:", label: "Sip", src: "/emojis/anime/sip.png", tags: ["sip"] },
  { shortcode: ":sleep_anim:", label: "Sleep", src: "/emojis/anime/sleep_anim.gif", tags: ["sleep"] },
  { shortcode: ":sleep_2:", label: "Sleep 2", src: "/emojis/anime/sleep_2.png", tags: ["sleep", "2"] },
  { shortcode: ":smug_think:", label: "Smug Think", src: "/emojis/anime/smug_think.png", tags: ["smug", "think"] },
  { shortcode: ":spin:", label: "Spin", src: "/emojis/anime/spin.gif", tags: ["spin"] },
  { shortcode: ":spin_2:", label: "Spin 2", src: "/emojis/anime/spin_2.gif", tags: ["spin", "2"] },
  { shortcode: ":spinfaster:", label: "Spinfaster", src: "/emojis/anime/spinfaster.gif", tags: ["spinfaster"] },
  { shortcode: ":staffping:", label: "Staffping", src: "/emojis/anime/staffping.gif", tags: ["staffping"] },
  { shortcode: ":stare:", label: "Stare", src: "/emojis/anime/stare.png", tags: ["stare"] },
  { shortcode: ":sukuna_googoogaga:", label: "Sukuna Googoogaga", src: "/emojis/anime/sukuna_googoogaga.png", tags: ["sukuna", "googoogaga"] },
  { shortcode: ":sukuna_smirk:", label: "Sukuna Smirk", src: "/emojis/anime/sukuna_smirk.png", tags: ["sukuna", "smirk"] },
  { shortcode: ":tearsofjoy:", label: "Tearsofjoy", src: "/emojis/anime/tearsofjoy.gif", tags: ["tearsofjoy"] },
  { shortcode: ":think_anim:", label: "Think", src: "/emojis/anime/think_anim.png", tags: ["think"] },
  { shortcode: ":thinkmark:", label: "Thinkmark", src: "/emojis/anime/thinkmark.png", tags: ["thinkmark"] },
  { shortcode: ":thoughtfulrem:", label: "Thoughtfulrem", src: "/emojis/anime/thoughtfulrem.png", tags: ["thoughtfulrem"] },
  { shortcode: ":thumbs_up_meme:", label: "Thumbs Up Meme", src: "/emojis/anime/thumbs_up_meme.png", tags: ["thumbs", "up", "meme"] },
  { shortcode: ":tobi:", label: "Tobi", src: "/emojis/anime/tobi.png", tags: ["tobi"] },
  { shortcode: ":tobiramasmirk:", label: "Tobiramasmirk", src: "/emojis/anime/tobiramasmirk.png", tags: ["tobiramasmirk"] },
  { shortcode: ":toji_facepalm:", label: "Toji Facepalm", src: "/emojis/anime/toji_facepalm.png", tags: ["toji", "facepalm"] },
  { shortcode: ":trigered:", label: "Trigered", src: "/emojis/anime/trigered.png", tags: ["trigered"] },
  { shortcode: ":ultra:", label: "Ultra", src: "/emojis/anime/ultra.gif", tags: ["ultra"] },
  { shortcode: ":uncannychiyo:", label: "Uncannychiyo", src: "/emojis/anime/uncannychiyo.png", tags: ["uncannychiyo"] },
  { shortcode: ":usamiangry:", label: "Usamiangry", src: "/emojis/anime/usamiangry.png", tags: ["usamiangry"] },
  { shortcode: ":usamiscared:", label: "Usamiscared", src: "/emojis/anime/usamiscared.png", tags: ["usamiscared"] },
  { shortcode: ":usamishocked:", label: "Usamishocked", src: "/emojis/anime/usamishocked.png", tags: ["usamishocked"] },
  { shortcode: ":usamitroll:", label: "Usamitroll", src: "/emojis/anime/usamitroll.png", tags: ["usamitroll"] },
  { shortcode: ":vaporeon:", label: "Vaporeon", src: "/emojis/anime/vaporeon.gif", tags: ["vaporeon"] },
  { shortcode: ":wagurichibi:", label: "Wagurichibi", src: "/emojis/anime/wagurichibi.png", tags: ["wagurichibi"] },
  { shortcode: ":wagurihappy:", label: "Wagurihappy", src: "/emojis/anime/wagurihappy.gif", tags: ["wagurihappy"] },
  { shortcode: ":weary:", label: "Weary", src: "/emojis/anime/weary.png", tags: ["weary"] },
  { shortcode: ":weeb_run_naruto:", label: "Weeb Run Naruto", src: "/emojis/anime/weeb_run_naruto.gif", tags: ["weeb", "run", "naruto"] },
  { shortcode: ":yay:", label: "Yay", src: "/emojis/anime/yay.png", tags: ["yay"] },
  { shortcode: ":yee:", label: "Yee", src: "/emojis/anime/yee.gif", tags: ["yee"] },
  { shortcode: ":yougogirl:", label: "Yougogirl", src: "/emojis/anime/yougogirl.gif", tags: ["yougogirl"] },
  { shortcode: ":yuji_bruh:", label: "Yuji Bruh", src: "/emojis/anime/yuji_bruh.png", tags: ["yuji", "bruh"] },
  { shortcode: ":yuji_happy:", label: "Yuji Happy", src: "/emojis/anime/yuji_happy.gif", tags: ["yuji", "happy"] },
  { shortcode: ":yuji_oh:", label: "Yuji Oh", src: "/emojis/anime/yuji_oh.png", tags: ["yuji", "oh"] },
  { shortcode: ":yuji_salute:", label: "Yuji Salute", src: "/emojis/anime/yuji_salute.png", tags: ["yuji", "salute"] },
  { shortcode: ":yuta_happy:", label: "Yuta Happy", src: "/emojis/anime/yuta_happy.gif", tags: ["yuta", "happy"] },
  { shortcode: ":zerotwo_hypedfast:", label: "Zerotwo Hypedfast", src: "/emojis/anime/zerotwo_hypedfast.gif", tags: ["zerotwo", "hypedfast"] },
  { shortcode: ":zorolike:", label: "Zorolike", src: "/emojis/anime/zorolike.png", tags: ["zorolike"] },
];

/** Fast `:shortcode:` -> sticker lookup for chat rendering and the picker. */
export const ANIME_STICKER_MAP: Record<string, AnimeSticker> = ANIME_STICKERS.reduce(
  (acc, s) => {
    acc[s.shortcode] = s;
    return acc;
  },
  {} as Record<string, AnimeSticker>,
);

/** True if a `:shortcode:` is an image-only anime sticker (must NOT be unicode-
 *  converted by replaceShortcodes). */
export function isAnimeSticker(shortcode: string): boolean {
  return shortcode in ANIME_STICKER_MAP;
}
