// GENERATED — do not edit by hand.
// French search keywords for the unicode emoji picker (Unicode CLDR french).
// Accent-stripped + lowercased. Emojis without a CLDR entry are omitted.

export const EMOJI_KEYWORDS_FR: Record<string, string> = {
  "😀": "content dents emoticone grand heureux joyeux rieur rire souriant sourire super tres visage",
  "😃": "avec bouche content de dents emoticone formidable grand grands heureux la ouverte souriant sourire super tres visage yeux",
  "😄": "aux avec bouche content emoticone et grand heureux joyeux la les lol mdr mignon ouverte rieurs rire souriant souriants sourire tres visage yeux",
  "😁": "aux avec content de dents emoticone grand heureux rieurs ses souriant souriants sourire super toutes visage yeux",
  "😆": "ahah avec bouche content emoticone et fermes lol mdr ouverte plisses rire souriant sourire visage yeux",
  "😅": "avec de emoticone excite froid froides goutte nerveux souriant sourire stresse sueur sueurs une visage",
  "🤣": "aux content de drole emoticone hilare joyeux larmes lol mdr par pleurer qui rire rit rouler se terre tordre visage",
  "😂": "aux content de emoticone heureux joie larmes lol mdr pleurer riant rire sourire visage",
  "🙂": "avec content emoticone heureux leger souriant sourire un visage",
  "🙃": "emoticone incroyable l’envers renversee tete visage",
  "🫠": "disparaitre dissoudre fond fondre gene liquefie liquide qui sarcasme se visage",
  "😉": "blague clin d’œil emoticone faisant flirter plaisanter sexy un visage",
  "😊": "avec content emoticone heureux qui rieurs rougir rougit satisfait souriant souriants sourire visage yeux œil",
  "😇": "ange angelique aureole avec beni bible emoticone heureux innocent paix souriant sourire spirituel visage",
  "🥰": "adorer aimer amour avec beguin coeur coeurs cœurs je j’adore smiley souriant sourire t’aime visage",
  "😍": "amour amoureux avec cœur de emoticone en forme romantique souriant sourire visage yeux œil",
  "🤩": "avec dans des etoile etoiles grand heureux la les place presse sourire surexcite tete visage wow yeux",
  "😘": "amour avec baiser bise bisou bonjour bonne cœur embrasser emoticone envoyant et fait je nuit qui t’aime un une visage",
  "😗": "amour baiser bise bisou embrasser emoticone faisant fait je petit qui t’aime un une visage",
  "☺️": "avec content decontracte detendu emoticone fermes heureux les souriant sourire visage yeux",
  "😚": "avec baiser bise bisou embrasser emoticone faisant fait fermes les qui rougir rougissant un une visage yeux",
  "😙": "amour aux baiser bise bisou embrasser emoticone faisant fait fermes gros je qui rieurs souriants sourire t’aime un une visage yeux",
  "🥲": "avec emu fier heureux larme reconnaissant smiley soulage souriant touche une visage",
  "😋": "bon content delicieux emoticone faim heureux la langue manger miam qui savourer souriant sourire tire visage",
  "😛": "cool emoticone genial la langue qui super tire visage",
  "😜": "amusant blague clin d’œil emoticone et fait fou la langue loufoque marrant qui rigolo tire un visage œil",
  "🤪": "de folle fou fous grand large oeil petit tete yeux œil",
  "😝": "degoutant emoticone et ferme fermes fois gout horrible importe la langue les ne omd on peu plisses qui qu’une tire visage vit yeux œil",
  "🤑": "argent bouche dans dollars emoticone et la les yeux",
  "🤗": "calin emoticone fait gentil mains qui un visage",
  "🤭": "avec bouche devant la main malin oops oups rigole secret sur surprise une visage",
  "🫢": "avec bouche choque embarrasse et etonne gene impressionne la main ouverts stupefait sur surpris visage yeux",
  "🫣": "cacher captive coup doigts d’œil effraye entre fascine fixement jeter qui regarde regarder se ses timide un visage",
  "🤫": "avec bouche bruit chut dit doigt la pas qui silence sur tete un visage",
  "🤔": "emoticone en hum mediter penser pleine reflechir reflexion visage",
  "🫡": "armee bonne chance compris fait militaire ok oui qui respect salut un visage",
  "🤐": "avec bouche cousue eclair emoticone fermeture motus se secret taire visage",
  "🤨": "avec euh hein incredule les leve mefiant pas quoi releves sceptique sourcil sourcils surprise tete visage vrai",
  "😐": "chaud commentaires de drole emoticone expression froid gene importe marbre neutre ni pas peu rester rire sans visage",
  "😑": "emoticone expression importe inexpressif mecontent neutre peu sans visage",
  "😶": "bouche commentaires dire emoticone expression muet ne neutre rien sans se secret silence sourdine taire visage voix",
  "🫥": "cacher deprime disparaitre en introverti invisible pointilles se visage",
  "😶‍🌫️": "brouillard dans distrait le les nuages visage",
  "😏": "arrogant avec charmeur emoticone malin ricaner ruse seducteur sourire suffisant suspicieux un visage",
  "😒": "bizarre blase content emoticone enerve fache importe jaloux pas peu qui s’ennuie visage",
  "🙄": "agace au ciel des emoticone excede incredulite les leve qui roulant roule roulement visage yeux",
  "😬": "dents emoticone gene grimacant grimace rien sourire visage",
  "😮‍💨": "chuchoter decourage decu expirant expiration extenue fatigue siffler souffler soulagement soupir sursaut visage",
  "🤥": "de dont emoticone le mensonge menteur nez pinocchio s’allonge visage",
  "🫨": "choc de etourdi fou omg ouah panique secoue surprenant terre tremblement vibration visage",
  "🙂‍↔️": "horizontalement non secouee secouer tete",
  "🙂‍↕️": "de hochement oui secouee tete verticalement",
  "😌": "calme emoticone serenite soulage soulagement visage zen",
  "😔": "abattu decu emoticone horrible mort pensif perdu triste visage",
  "😪": "emoticone endormi fatigue larme pleurer sommeil triste visage",
  "🤤": "bave baver delicieux emoticone mmh qui visage",
  "😴": "bonne coucher dormir emoticone endormi fatigue nuit sieste sommeil somnolent visage zzz",
  "😷": "avec bacteries chirurgical dentiste docteur emoticone germes malade masque medecin rhume visage",
  "🤒": "avec indispose malade thermometre visage",
  "🤕": "aie autour avec bandage blessure bobo de emoticone la pansement tete un visage",
  "🤢": "degoutant ecœure emoticone la malade nausee nauseeux qui vert visage vomir",
  "🤮": "gerbe gerber malade qui tete visage vomi vomissure vomit",
  "🤧": "atchoum emoticone eternue eternuement eternuer fievre grippe malade moucher mouchoir qui rhume se souhaits tes visage",
  "🥵": "chaleur chaud coup de et fievre rouge sue suer tout toute transpiration trop visage",
  "🥶": "bleu ca caille et froid gel gele gelure glace glacial glacon visage",
  "🥴": "bouche bourre bourree clair dans emeche hebete les ondulee pas pompette qui rond saoul souler tete tourne vapes visage",
  "😵": "avec emoticone etourdi fatigue le malade mort tournis visage",
  "😵‍💫": "aux confusion en etourdi hagard la malade nausee ouh qui spirales tete tourne visage yeux",
  "🤯": "choc choque choquee explose qui surpris surprise tete",
  "🤠": "avec chapeau cowboy de visage",
  "🥳": "anniversaire celebration chapeau de emoticone festif fete heureux hourra joyeux pointu sifflet visage youpi",
  "🥸": "deguise deguisement ebouriffes espion faux grimer incognito lunettes moustache nez postiche smiley sourcils visage",
  "😎": "avec cool de lunettes pose soleil tranquille visage",
  "🤓": "classe de doue fute geek idiot intelligent la lunettes personne premier ringard surdoue tronche visage",
  "🧐": "avec classe collet fortune jeu monocle monte riche tete un vieux visage",
  "😕": "confus desole emoticone ennuye je ne pas sais triste visage",
  "🫤": "avec bof bouche confus decu diagonale en euh frustration incertain sceptique visage",
  "😟": "anxieux emoticone inquiet preoccupe stresse surpris triste visage",
  "🙁": "emoticone legerement mecontent triste visage",
  "☹️": "emoticone malheureux mecontent triste visage",
  "😮": "avec bee bouche choque emoticone epate etonne incroyable la omd oubli ouverte surpris visage",
  "😯": "bouche ebahi emoticone incroyable la omd ouverte sans stupefait stupeur surpris visage voix",
  "😲": "choc choque emoticone etonne impossible incroyable omd stupefait visage",
  "😳": "chaud comment ebahi emoticone etonne gene impressionne incredule incroyable qui quoi rouge rougit visage",
  "🥺": "battus chiens de embarrasse excuse gros implorant pardon pitie plait supplication supplie s’il te visage yeux",
  "🥹": "admiration de emu fierte gratitude joie larmes pleurs retenant retenir ses triste visage",
  "😦": "au avec bouche decu depourvu effraye emoticone mecontent ouverte peur pris surpris visage",
  "😧": "angoisse comment emoticone hein mecontent oubli peur quoi stresse surpris terrifie visage",
  "😨": "anxieux apeure bleme effraye emoticone inquiet peur terrifie visage",
  "😰": "aah anxieux avec bee bleu bleue bouche de effraye emoticone en froid froides goutte mince nerveux ouverte peur sueur sueurs terrifie visage",
  "😥": "decu emoticone mais ouf pfiou soulage sueur triste visage",
  "😢": "emoticone horrible larme larmes malheureux pleure pleurer qui triste visage",
  "😭": "chaudes emoticone larme larmes malheureux pleure pleurer pleurs qui sangloter triste visage",
  "😱": "choque cri de effraye hurle munch omd peur qui surpris terreur visage",
  "😖": "confus deconcerte emoticone fache fermes frustre irrite triste visage yeux",
  "😣": "concentre de emoticone mal migraine perseverant tete visage",
  "😞": "abattu affreux decourage decu emoticone malheureux tort triste visage",
  "😓": "avec de demoralise emoticone et froide froides goutte mal migraine mince ouf peur sueur sueurs tete triste visage",
  "😩": "echec emoticone epuise faim fatigue las mecontent non pleurer sommeil triste visage",
  "😫": "contrarie emoticone fatigue mecontent triste visage",
  "🥱": "baillant baille bailler dormir emoticone ennui fatigant fatigue sieste visage",
  "😤": "avec colere des emoticone enerve fache fumee mecontent narines sortant triomphe victoire visage",
  "😡": "boudeur colere de emoticone enerve exaspere fache fronces furieux mecontent rageur rouge sourcils visage",
  "😠": "colere emoticone en exaspere fache fronces frustre mecontent rageur sourcils visage",
  "🤬": "avec bouche censure colere dans des gros insulter insultes jurer juron la mots sur symboles tete visage",
  "😈": "avec cornes des emoticone fache fantastique souriant sourire visage",
  "👿": "avec colere cornes demon des diable diablotin emoticone en fantastique malicieux mauvais visage",
  "💀": "corps crane de dead fantastique je mort squelette suis tete visage yolo",
  "☠️": "crane de mort os tete",
  "💩": "bande bd caca crotte de dessin dessinee excrement mauvais odeur popo puer sentir tas visage",
  "🤡": "clown de emoticone maquillage visage",
  "👹": "creature effrayant fantastique japonais masque monstre ogre",
  "👺": "colere creature fantastique farfadet japonais masque mechant monstre",
  "👻": "blague bouh creature de effrayant fantastique fantome halloween hanter monstre peur visage",
  "👽": "alien creature emoticone espace extraterrestre monstre ovni science-fiction visage",
  "👾": "alien creature de envahisseur espace extraterrestre fantastique jeu l’espace monstre ovni pixels video",
  "🤖": "androide automate de machine monstre robot visage",
  "😺": "animal bouche chat ouverte qui sourire sourit visage",
  "😸": "animal avec chat des grand qui rieurs souriants sourire sourit un visage yeux",
  "😹": "animal aux chat de joie larmes lol mdr pleure pleurer qui rire rit",
  "😻": "amour amoureux aux avec chat coeurs cœur cœurs dans des en les souriant sourire yeux",
  "😼": "animal avec chat coin de en ironique narquois sourire tete visage",
  "😽": "animal avec baiser bise bisou chat de embrasse embrasser fait fermes les qui tete un une yeux",
  "🙀": "animal avec bouche chat de fatigue inquiet la oh ouverte surpris tete visage",
  "😿": "animal chat de larme pleure pleurer qui tete triste visage",
  "😾": "animal boude bouder chat colere de desaccord en ennui qui tete visage",
  "🙈": "animal cache effraye embarras entendu gene geste interdit ne non omd oubli pas peur rien secret singe visage voir vu yeux",
  "🙉": "animal ecouter entendre entendu geste interdit ne non oreilles pas rien secret singe sourd visage vu",
  "🙊": "animal bouche chut cousue dire geste interdit motus muet ne non parler rien se secret silence singe taire visage",
  "💌": "amour cœur d’amour lettre saint-valentin",
  "💘": "amour coeur cupidon cœur et fleche sentiment transperce",
  "💝": "amour anniversaire avec cœur ruban saint-valentin sentiment",
  "💖": "amour cœur etincelant etincelles sentiment",
  "💗": "amour bat battant cœur grandissant pulsations qui sentiment",
  "💓": "amour bat battant cardio cœur pulsations qui sentiment",
  "💞": "amour anniversaire cœurs deux qui sentiment tourbillon tournent",
  "💕": "amour anniversaire cœurs deux petits rendez-vous roses sentiment",
  "💟": "amour avec blanc cœur decoration decore sentiment violet",
  "❣️": "amour cœur d’exclamation exclamation point ponctuation",
  "💔": "amour brise cœur malheureux sentiment separe triste",
  "❤️‍🔥": "amour cœur desir enflamme feu passion",
  "❤️‍🩹": "avec bandages cœur reconforter reparer soigner",
  "❤️": "amour cœur rouge sentiment",
  "🩷": "143 adorable aimer amour cœur emotion jtm mignon rose",
  "🧡": "coeur cœur orange",
  "💛": "amour cœur jaune sentiment",
  "💚": "amour cœur sentiment vert",
  "💙": "amour bleu cœur sentiment",
  "🩵": "143 aimer amour bleu ciel clair cyan cœur emotion jtm mignon special",
  "💜": "amour cœur sentiment violet",
  "🤎": "brun cœur marron",
  "🖤": "cœur noir",
  "🩶": "143 amour ardoise argent argente cœur emotion gris jtm special",
  "🤍": "blanc cœur",
  "💋": "baiser bise bisou bouche de embrasser levres rendez-vous rouge sexy trace",
  "💯": "100 cent points score",
  "💢": "bande bd colere de dessin dessinee furieux symbole",
  "💥": "bande bd bombe boum collision dessinee detonation etincelles explosion",
  "💫": "bande bd des dessinee etincelles etoile etoiles etourdissement filante tournis voir",
  "💦": "bande bd de dessinee eau eclabousser eclaboussures effort entrainement gouttes sueur",
  "💨": "bande bd courant decamper deguerpir dessinee detaler en filer fumee nuage partir pet vent vite",
  "🕳️": "trou",
  "💬": "bande bd bulle de dessinee dialogue ecrire message parole sms",
  "👁️‍🗨️": "bande bd bulle dans de dessinee temoin une voir œil",
  "🗨️": "bulle de dialogue gauche parole",
  "🗯️": "bande bd bulle colere crier dessinee droite hurler",
  "💭": "bande bd bulle de dessinee idee imaginer inventer invention pensee penser reve rever",
  "💤": "bande bd bonne dessinee dormir endormi fatigue nuit ronfler zzz",
  "🧑": "adulte genre neutre non-genre",
  "👋": "au bientot bonjour bye coucou de hello il la main plus quelqu’un qui revoir salue salut signe tard",
  "🤚": "de dos levee main",
  "🖐️": "doigts ecartes levee main paume stop",
  "✋": "de feuille la levee main paume stop tope",
  "🖖": "doigts main salut spock star trek vulcain",
  "🫱": "droite la main serrer tenir vers",
  "🫲": "gauche la main serrer tenir vers",
  "🫳": "bas chasser choisir faire laisser le main ouste partir paume rejeter tomber vers",
  "🫴": "appeler attirer de faire haut la le main offre paume venir vers",
  "🫷": "arreter attendre bloquer cinq five gauche halte high la main m’en pousse pousser qui refuser stop tape top vers",
  "🫸": "arreter attendre bloquer cinq droite five halte high la main m’en pousse pousser qui refuser stop tape top vers",
  "👌": "bien compris d’accord geste main nickel ok parfait super tout va",
  "🤌": "agacement argumentation avec bout des doigts geste interrogation joints les main mains parler patience silence",
  "🤏": "deux doigts et index petit petite peu pouce quantite rapproches somme un",
  "✌️": "amour and ciseaux de doigts et la love main paix peace victoire",
  "🤞": "bonne chance croises doigts main",
  "🫰": "amour argent avec cher claquer croises cœur des doigts et index main pouce",
  "🤟": "amour doigts geste ily je main pour signe trois t’aime",
  "🤘": "avec cornes diable doigts du les main rock rock’n roll yeah",
  "🤙": "appel avec doigts les main signe telephone telephonique",
  "👈": "avec doigt gauche index la main pointant pointe vers",
  "👉": "avec doigt droite index la main pointant pointe vers",
  "👆": "avec doigt haut index le main montrer pointant vers",
  "🖕": "doigt d’honneur main majeur",
  "👇": "avec bas doigt index le main montrer pointant vers",
  "☝️": "doigt haut index le main moi pointant pointe vers",
  "🫵": "index l’utilisateur pointant pointer toi vers",
  "👍": "aussi bien compris d’accord genial haut le leve main moi ok oui pouce super top vers",
  "👎": "baisse bas le main mauvais non nul pouce vers",
  "✊": "leve main pierre poing serre solidarite",
  "👊": "absolument battre boum correct coup de d’accord face main mon poing pote serrer",
  "🤛": "fistbump gauche main poing",
  "🤜": "droite main poing",
  "👏": "applaudissements applaudissent bien bon bravo felicitations formidable geste joue mains qui super travail",
  "🙌": "air en geste hourra levees l’air mains youpi",
  "🫶": "amour cœur forment mains qui un",
  "👐": "ecartees main mains ouvert ouvertes",
  "🤲": "contre des doigts ensemble esperer haut le mains paume paumes prier priere vers",
  "🤝": "conclu de d’accord la main mains marche poignee presentation rencontre serrer",
  "🙏": "contre dans demander en felicitations la l’autre l’une main mains merci plait prier priere salut se s’il taper te tope vous",
  "✍️": "ecrire ecrit main qui",
  "💅": "cosmetiques importe manucure maquillage ongles peu s’ennuyer vernis",
  "🤳": "appareil photo selfie telephone",
  "💪": "bande bd biceps bodybuilding contracte corps culturisme dessinee entrainement exercice force halterophilie muscle muscles soulever",
  "🦾": "accessibilite bras de handicap mecanique prothese robot",
  "🦿": "accessibilite artificielle de handicap jambe mecanique prothese robot",
  "🦵": "coup cuisse de flechi genou genoux jambe membre pied",
  "🦶": "cheville coup de lourd pas pied",
  "👂": "corps ecouter entendre oreille ouie son",
  "🦻": "accessibilite appareillee auditive handicap malentendant oreille prothese sonotone sourd surdite",
  "👃": "corps narines nez odeur sentir",
  "🧠": "cerveau intelligent intelligente",
  "🫀": "anatomie battement battements cardiologie coeur cœur de organe pouls pulsation",
  "🫁": "anatomie expiration inspiration organe poumons respiration respirer souffle",
  "🦷": "carie dent dentiste diamant email",
  "🦴": "chien halloween os squelette",
  "👀": "chercher corps coup d’œil regarder visage voir yeux œil",
  "👁️": "corps œil",
  "👅": "corps langue lecher",
  "👄": "baiser beaute bise bisou bouche corps embrasser levres rouge",
  "🫦": "anxieux flirt inquiet levre levres l’aise mal mordent mordue nerveux qui se",
  "👶": "bebe emoticone enceinte enfant nouveau-ne petit",
  "🧒": "enfant genre jeune neutre non-genre",
  "👦": "emoticone enfant garcon jeune personne",
  "👧": "couettes emoticone enfant fille grands jeune nattes personne petite tresses vierge visage yeux zodiaque",
  "👱": "blond blonde cheveux garcon homme humain personne tete visage",
  "👨": "ami garcon homme personne petit pote",
  "🧔": "avec barbe barbu barbue personne une",
  "🧔‍♂️": "barbe barbu homme",
  "🧔‍♀️": "barbe barbue femme",
  "👩": "blonde cheveux coupe de femme personne",
  "👱‍♀️": "blonde cheveux femme personne",
  "👱‍♂️": "blond cheveux homme",
  "🧓": "adulte age agee genre neutre non-genre personne",
  "👴": "age agee chauve emoticone grand-pere homme monsieur papi personne sage vieux",
  "👵": "agee blonde dame emoticone femme grand-mere mamie personne sage",
  "🙍": "contente contrariee decue embetee femme froncant froncer genee geste les mecontente pas personne sourcils triste",
  "🙍‍♂️": "froncant froncement geste homme les mecontent renfrogne sourcils",
  "🙍‍♀️": "femme froncant froncement geste les sourcils",
  "🙎": "boude bouder decue enervee expression fachee faire femme froncer geste inquiete la les moue personne qui sourcils tete",
  "🙎‍♂️": "boude bouder faire geste homme la moue qui",
  "🙎‍♀️": "boude femme geste qui",
  "🙅": "aucune bloquer chance d’interdiction faisant femme geste impossible interdit main niet non pas personne possible stop un",
  "🙅‍♂️": "d’interdiction faisant geste homme interdit main non un",
  "🙅‍♀️": "d’interdiction faisant femme geste interdit main un",
  "🙆": "bras danser d’acceptation d’accord exercice faisant femme geste grandir les lever main ok personne un",
  "🙆‍♂️": "d’acceptation d’accord faisant geste homme main ok un",
  "🙆‍♀️": "d’acceptation d’accord faisant femme geste main ok un",
  "💁": "aide diva femme haut importe information insouciante le main paume personne peu potins pretentieuse sarcastique sophistique vers",
  "💁‍♂️": "aide apporter avec diva haut homme importe informations insolent le main paume peu potins sarcastique vers",
  "💁‍♀️": "femme haut le paume vers",
  "🙋": "compte content femme geste ici je la leve levee main moi participer personne presente qui sais sur",
  "🙋‍♂️": "geste homme je la leve levee main moi personne qui repondre sais",
  "🙋‍♀️": "femme geste la leve levee main qui",
  "🧏": "accessibilite entendre malentendant oreille personne sourd sourde surdite",
  "🧏‍♂️": "accessibilite entendre homme malentendant oreille sourd",
  "🧏‍♀️": "accessibilite entendre femme malentendant oreille sourd sourde",
  "🙇": "compris confus desole excuses geste gronder incline inclinee j’ai ok pardon personne qui s’incline",
  "🙇‍♂️": "desole geste homme incline qui s’incline",
  "🙇‍♀️": "desolee excuses femme geste inclinee meditation mediter prosterne qui se s’incline",
  "🤦": "avec de drame exasperation femme geste incredulite incroyable j’en la le main pas paume personne peux plus possible sur visage",
  "🤦‍♂️": "avec encore exasperation homme incredulite incroyable la le main non oh oubli paume personne sur visage",
  "🤦‍♀️": "avec crois encore exasperation femme incredulite incroyable j’y la le main non oh oubli pas paume personne sur visage",
  "🤷": "aucune ca comme c’est doute d’epaules epaules faire femme hausse haussement idee ignorance indifference je les ne pas personne peut-etre que qui sais sait",
  "🤷‍♂️": "aucune doute d’epaules epaules hausse haussement homme idee ignorance indifference les moi pas personne qui rien sais vu",
  "🤷‍♀️": "aucune doute d’epaules epaules femme hausse haussement idee ignorance indifference je les moi pas personne qui rien sais vu",
  "🧑‍⚕️": "(tous de docteur genres) infirmier la medecin professionnel sante therapeute",
  "👨‍⚕️": "de docteur homme infirmier la medecin medicale metier profession professionnel sante",
  "👩‍⚕️": "de docteur docteure femme infirmiere la medecin medicale metier profession professionnelle sante",
  "🧑‍🎓": "(tous diplome etudiant etudiante genres)",
  "👨‍🎓": "diplome etudiant homme",
  "👩‍🎓": "diplomee etudiante femme",
  "🧑‍🏫": "enseignant enseignante formateur formatrice personnel professeur",
  "👨‍🏫": "enseignant homme instituteur instructeur metier professeur",
  "👩‍🏫": "enseignante femme institutrice instructrice professeure",
  "🧑‍⚖️": "balance juge",
  "👨‍⚖️": "balance homme juge justice metier",
  "👩‍⚖️": "balance femme juge justice metier",
  "🧑‍🌾": "(tous fermier fermiere genres) jardinier jardiniere",
  "👨‍🌾": "agriculteur fermier homme jardinier metier",
  "👩‍🌾": "agricultrice femme fermiere jardiniere metier",
  "🧑‍🍳": "(tous chef cuisinier cuisiniere genres)",
  "👨‍🍳": "chef cuisinier homme metier",
  "👩‍🍳": "chef cuisiniere femme metier",
  "🧑‍🔧": "(tous artisan electricien electricienne genres) mecanicien mecanicienne plombier",
  "👨‍🔧": "electricien homme mecanicien mecanique metier ouvrier plombier",
  "👩‍🔧": "electricienne femme mecanicienne mecanique metier ouvriere plombier",
  "🧑‍🏭": "(tous assemblage genres) industrie ouvrier ouvriere usine",
  "👨‍🏭": "assemblage homme industrie metier montage ouvrier usine",
  "👩‍🏭": "assemblage femme industrie metier montage ouvriere usine",
  "🧑‍💼": "(tous affaires architecte bureau de employe employee genres)",
  "👨‍💼": "affaires architecte bureau cadre de directeur employe homme metier",
  "👩‍💼": "affaires architecte bureau cadre de directrice employee femme metier",
  "🧑‍🔬": "chimiste scientifique",
  "👨‍🔬": "biologiste chimiste homme ingenieur mathematicien metier physicien scientifique",
  "👩‍🔬": "biologiste chimiste femme ingenieure mathematicienne metier physicienne scientifique",
  "🧑‍💻": "(tous developpeur developpeuse genres) informaticien informaticienne logiciels technologie",
  "👨‍💻": "codeur developpeur homme informaticien inventeur logiciels metier technologie",
  "👩‍💻": "codeuse developpeuse femme informaticienne inventrice logiciels metier technologie",
  "🧑‍🎤": "(tous artiste chanteur chanteuse genres) rock star",
  "👨‍🎤": "acteur artiste chanteur homme metier rock rockeur star",
  "👩‍🎤": "actrice artiste chanteuse femme metier rock rockeuse star",
  "🧑‍🎨": "artiste palette",
  "👨‍🎨": "artiste homme metier palette peintre",
  "👩‍🎨": "artiste femme metier palette peintre",
  "🧑‍✈️": "avion pilote",
  "👨‍✈️": "avion homme metier pilote",
  "👩‍✈️": "avion femme metier pilote",
  "🧑‍🚀": "astronaute fusee",
  "👨‍🚀": "astronaute casque cosmonaute espace fusee homme metier spationaute",
  "👩‍🚀": "astronaute casque cosmonaute espace femme fusee metier spationaute",
  "🧑‍🚒": "camion de pompier pompiers",
  "👨‍🚒": "camion casque de homme metier pompier pompiers",
  "👩‍🚒": "camion casque de femme metier pompier pompiers",
  "👮": "autorite de flic homme loi metier officier personne police policier tenue uniforme",
  "👮‍♂️": "flic homme officier police policier",
  "👮‍♀️": "autorite femme flic loi metier officier personne police policiere tenue uniforme",
  "🕵️": "detective enqueteur espion homme",
  "🕵️‍♂️": "detective enqueteur espion homme",
  "🕵️‍♀️": "detective enqueteuse enquetrice espionne femme",
  "💂": "buckingham casque garde homme londres palace",
  "💂‍♂️": "garde homme",
  "💂‍♀️": "buckingham casque femme garde londres metier palace",
  "🥷": "assassin combat furtif guerrier masque ninja personne sabre secret soldat",
  "👷": "batiment btp casque chantier construction du homme metier ouvrier personne personnel reparer",
  "👷‍♂️": "batiment du homme ouvrier",
  "👷‍♀️": "batiment casque chantier de du femme metier ouvrier ouvriere",
  "🫅": "avec couronne monarque noble personne royal royaute une",
  "🤴": "couronne prince royal royaute",
  "👸": "conte couronne de fantastique fees personne princesse reine",
  "👳": "avec en homme oriental personne turban visage",
  "👳‍♂️": "en homme turban",
  "👳‍♀️": "avec en femme turban",
  "👲": "avec casquette chapeau chinoise homme mao",
  "🧕": "avec bandana femme foulard hijab mantilla tichel un voile",
  "🤵": "elegant en homme marie mariee personne smoking",
  "🤵‍♂️": "en homme smoking",
  "🤵‍♀️": "en femme smoking",
  "👰": "avec mariage mariee personne voile",
  "👰‍♂️": "avec homme voile",
  "👰‍♀️": "avec femme voile",
  "🤰": "enceinte femme",
  "🫃": "enceint enceinte grossesse homme mange personne trop ventre",
  "🫄": "enceinte grossesse mange personne trop ventre",
  "🤱": "allaitement bebe le maman nourrice nourrir sein soins",
  "👩‍🍼": "allaitant allaitement bebe biberon femme maman mere nounou nouveau-ne personne un",
  "👨‍🍼": "allaitant allaitement bebe biberon homme nouveau-ne papa pere personne un",
  "🧑‍🍼": "allaitant allaitement bebe biberon homme maman mere nounou nouveau-ne papa pere personne un",
  "👼": "ailes ange aureole bebe eglise emoticone fantastique visage",
  "🎅": "bonnet claus fetes magie noel pere santa tradition",
  "🤶": "bonnet fetes mere noel santa",
  "🧑‍🎄": "joyeux noel papa pere personne saint-nicolas santa",
  "🦸": "bien cape force heroine heros le monde personnage pouvoir sauver super super-heros super-pouvoir superheros superman vengeur voler",
  "🦸‍♂️": "bien heros homme super-heros super-pouvoir",
  "🦸‍♀️": "bien femme heroine heros super-heroine super-pouvoir",
  "🦹": "cape criminel deguisement diabolique mal mauvais mechant personnage pouvoir super super-pouvoir super-vilain vilain",
  "🦹‍♂️": "criminel homme mal mechant super-pouvoir super-vilain",
  "🦹‍♀️": "criminelle femme mal mechante super-pouvoir super-vilain",
  "🧙": "chapeau de enchantement ensorceleur envoutement jeu mage magicien personnage role sorcier sorciere sortilege",
  "🧙‍♂️": "homme mage magicien sorcier",
  "🧙‍♀️": "ensorceleuse femme mage sorciere",
  "🧚": "ailes clochette deguisement fee feerie feerique magie oberon personnage puck titania voler",
  "🧚‍♂️": "feetaud oberon puck",
  "🧚‍♀️": "fee titania",
  "🧛": "canines cape conte deguisement dents dracula halloween mort-vivant personnage sang vampire",
  "🧛‍♂️": "dracula homme mort-vivant vampire",
  "🧛‍♀️": "femme morte-vivante vampire",
  "🧜": "aquatique ariel creature de folklore mer ocean personnage petite poisson queue sirene trident triton",
  "🧜‍♂️": "triton",
  "🧜‍♀️": "sirene",
  "🧝": "anneaux conte des elf elfe le legolas magique oreilles personnage seigneur",
  "🧝‍♂️": "elfe homme magique",
  "🧝‍♀️": "elfe femme magique",
  "🧞": "aladin djinn genie homme lampe magie magique personnage souhait voeu vœu",
  "🧞‍♂️": "djinn genie homme",
  "🧞‍♀️": "djinn femme genie",
  "🧟": "effrayant flippant halloween horreur mort mort-vivant personnage peur vivant zombie",
  "🧟‍♂️": "homme mort-vivant zombie",
  "🧟‍♀️": "femme morte-vivante zombie",
  "🧌": "conte de fees legende monstre mythe troll troller",
  "💆": "detente fait femme fermer les massage masser personne qui relaxation repos salon se tete therapie visage yeux zen",
  "💆‍♂️": "apaiser de fait homme le mal massage masser migraine qui relaxation salon se tension tete visage",
  "💆‍♀️": "fait femme massage masser qui se visage",
  "💇": "barbier beaute cheveux ciseaux coiffure coupe couper de fait femme les personne qui salon se style",
  "💇‍♂️": "cheveux chez coiffeur coiffure coupe couper de fait homme le les qui salon se",
  "💇‍♀️": "cheveux coiffure couper fait femme les qui se",
  "🚶": "balade balader en flaner homme marche marcher nonchalant personne pieton promenade qui route se",
  "🚶‍♂️": "homme marche pieton qui",
  "🚶‍♀️": "femme marche marcher pietonne qui randonneuse",
  "🧍": "debout personne",
  "🧍‍♂️": "debout homme",
  "🧍‍♀️": "debout femme",
  "🧎": "genoux personne priere religion",
  "🧎‍♂️": "genoux homme",
  "🧎‍♀️": "femme genoux",
  "🧑‍🦯": "accessibilite avec aveugle blanche canne personne une",
  "👨‍🦯": "accessibilite avec aveugle blanche canne deficient handicap homme malvoyant visuel",
  "👩‍🦯": "accessibilite avec aveugle blanche canne deficiente femme handicap malvoyante visuelle",
  "🧑‍🦼": "accessibilite en fauteuil motorise personne roulant",
  "👨‍🦼": "accessibilite en fauteuil handicap homme motorise roulant",
  "👩‍🦼": "accessibilite en fauteuil femme handicap motorise roulant",
  "🧑‍🦽": "accessibilite en fauteuil manuel personne roulant",
  "👨‍🦽": "accessibilite en fauteuil handicap homme manuel roulant",
  "👩‍🦽": "accessibilite en fauteuil femme handicap manuel roulant",
  "🏃": "arriver coureur courir course court homme jogging marathon marathonien personne pied presse qui rapide sportif vite",
  "🏃‍♂️": "course court homme jogging marathon pied qui",
  "🏃‍♀️": "course court depecher femme joggeuse jogging marathon pied qui running se vite vitesse",
  "💃": "danse danser danseuse femme fete flamenco qui rythme salsa sortir tango",
  "🕺": "danse danseur femme fete flamenco homme qui rythme salsa",
  "🕴️": "affaires costume d’affaires en homme levitation",
  "👯": "amies avec bunny danseuse de deguisement des double femme femmes fete fille filles jumelles lapin oreilles personnes synchro",
  "👯‍♂️": "amis avec danseur de des faire fete homme hommes la lapin oreilles",
  "👯‍♀️": "avec danseuse de des femme femmes fete lapin oreilles",
  "🧖": "au bien-etre chaud dans detente hammam personne relaxation sauna spa un vapeur",
  "🧖‍♂️": "au hammam homme sauna",
  "🧖‍♀️": "au femme hammam sauna",
  "🧗": "alpiniste escalade escalader grimpe grimper grimpeur montagne personne qui sport",
  "🧗‍♂️": "alpiniste grimpe grimpeur homme qui",
  "🧗‍♀️": "alpiniste femme grimpe grimpeuse qui",
  "🤺": "epee escrime escrimeur escrimeuse personne sport",
  "🏇": "cheval chevaux course de hippique jockey sport",
  "⛷️": "neige ski skieur sport",
  "🏂": "homme neige ski snowboard snowboardeur sport",
  "🏌️": "balle de golf golfeur green homme joueur personne pga pitch sport",
  "🏌️‍♂️": "golf golfeur homme",
  "🏌️‍♀️": "femme golf golfeuse practice sport",
  "🏄": "du faisant glisse homme mer ocean personne plage planche sport surf vagues",
  "🏄‍♂️": "homme surf surfeur",
  "🏄‍♀️": "femme mer ocean plage sport surf surfeuse vagues",
  "🚣": "barque bateau dans lac naviguer peche personne ramant ramer rameur riviere sport une",
  "🚣‍♂️": "barque bateau dans homme rameur une",
  "🚣‍♀️": "barque bateau dans femme lac navigation peche plaisance ramer rameuse riviere sport une",
  "🏊": "crawl eau exercice homme nage nageant nageur natation personne piscine sport",
  "🏊‍♂️": "homme nage nageur",
  "🏊‍♀️": "femme nage nageuse natation sport",
  "⛹️": "athletique avec ballon basket-ball basketteur dribble joueur match personne rebond sport",
  "⛹️‍♂️": "avec ballon homme",
  "⛹️‍♀️": "avec ballon basket-ball basketteuse femme sport",
  "🏋️": "bodybuilding des entrainement force halterophile halterophilie homme lever muscles personne poids sport",
  "🏋️‍♂️": "halterophile homme",
  "🏋️‍♀️": "entrainement exercice femme halterophile sport",
  "🚴": "course cycliste de france guidon homme pedaler personne rouler sport tour velo",
  "🚴‍♂️": "cyclisme cycliste homme velo",
  "🚴‍♀️": "cyclisme cycliste femme sport velo",
  "🚵": "coureur cyclisme de en france grimper homme montagne personne sport tour velo vtt",
  "🚵‍♂️": "cycliste en homme velo vtt",
  "🚵‍♀️": "cycliste en femme montagne sport velo vtt vttiste",
  "🤸": "agilite athlete faire faisant femme gymnaste gymnastique la personne roue sport",
  "🤸‍♂️": "acrobatie content faire faisant garcon gymnastique homme la personne roue souple sport",
  "🤸‍♀️": "acrobatie exercice faire faisant femme gymnaste gymnastique la personne roue sport",
  "🤼": "bataille de faisant la lutte lutteur lutteurs personnes sport",
  "🤼‍♂️": "athletes bataille force hommes le lutte lutteurs personne personnes ring sport sur",
  "🤼‍♀️": "bataille combat duel femmes lutte lutteuse lutteuses personne personnes sport",
  "🤽": "au ballon homme jouant joue personne piscine qui sport water-polo",
  "🤽‍♂️": "ballon de eau homme jeu joueur match personne piscine sport water-polo",
  "🤽‍♀️": "ballon de femme joueuse nager personne piscine sport water-polo",
  "🤾": "athlete au ballon handball handballeur jouant lancer personne sport",
  "🤾‍♂️": "handball handballeur homme sport",
  "🤾‍♀️": "athlete attaquante ballon femme handball handballeuse personne sport tir",
  "🤹": "artiste cirque gerer jongle jongler jongleur multitache personne qui",
  "🤹‍♂️": "acrobatie artiste balles cirque homme jonglage jongleur multitache personne",
  "🤹‍♀️": "femme jonglage jongleuse multitache",
  "🧘": "assise dans detendu du en femme la lotus meditation personne position posture relax relaxation tailleur yoga zen",
  "🧘‍♂️": "dans du homme la lotus meditation position posture yoga",
  "🧘‍♀️": "dans du femme la lotus meditation position posture yoga",
  "🛀": "baignoire bain personne prenant prend qui un",
  "🛌": "au auberge bonne coucher dodo dormir fatigue hotel lit nuit personne sieste",
  "🧑‍🤝‍🧑": "couple de deux gay homosexuel la main par personne personnes poignee se tenant tenir",
  "👭": "amie amies amitie amoureuses couple dans deux donnant femmes filles gay homosexuelles jumelles la lesbiennes lgbt lgbtq lgbtqia main meilleures petite rendez-vous se sœurs tenant",
  "👫": "ami amie amis amoureux couple dans donnant et femme homme la main petit petite rendez-vous se tenant",
  "👬": "ami amis amitie amoureux couple dans deux donnant fils freres gay gemeaux hommes homosexuels jumeaux la lgbt main meilleurs petit rendez-vous se tenant zodiaque",
  "💏": "amour anniversaire baiser bisou couple femme homme",
  "💑": "amour anniversaire avec couple cœur femme homme rendez-vous",
  "🗣️": "parle parler qui silhouette tete",
  "👤": "buste de mystere ombre silhouette",
  "👥": "ami amie amies amis bff bustes de gens le meilleur meilleure meilleures meilleurs monde personnes silhouettes tout",
  "🫂": "accolade amitie au bonjour calin embrassades etreinte gratitude merci personne revoir",
  "👪": "avec enfant et famille femme fils garcon homme mere pere pere, un une",
  "🧑‍🧑‍🧒": "adulte adulte, enfant famille",
  "🧑‍🧑‍🧒‍🧒": "adulte adulte, enfant enfant, famille",
  "🧑‍🧒": "adulte adulte, enfant famille monoparentale",
  "🧑‍🧒‍🧒": "adulte adulte, enfant enfant, famille monoparentale",
  "👣": "de empreintes nus pas pied pieds traces",
  "🐻": "animal brun miel nounours ours teddy tete visage",
  "🐵": "animal curieux de georges le petit singe sourire tete visage",
  "🐒": "animal primate singe",
  "🦍": "animal gorille primate",
  "🦧": "animal orang-outan primate singe",
  "🐶": "animal chien chiot de domestique tete visage",
  "🐕": "aboyer animal chien domestique",
  "🦮": "accessibilite animal aveugle chien guide malvoyant non-voyant",
  "🐕‍🦺": "accessibilite aide animal assistance chien chien-guide d’assistance handicap",
  "🐩": "animal caniche chien",
  "🐺": "animal de loup louve tete",
  "🦊": "animal nature renard tete visage",
  "🦝": "animal curieux laveur raton sournois",
  "🐱": "animal chat chaton de miaou minou tete",
  "🐈": "animal chat chaton domestique miaou miauler",
  "🐈‍⬛": "animal chat chaton felin halloween malchanceux matou miaou noir superstition",
  "🦁": "animal astrologie criniere de fort horoscope lion roi rugissement safari savane tete visage zodiaque",
  "🐯": "animal de felin predateur tete tigre visage",
  "🐅": "animal felin predateur tigre tigresse zoo",
  "🐆": "animal felin leopard predateur zoo",
  "🐴": "animal cheval de dressage equitation ferme jument tete",
  "🫎": "animal bois cervide elan mammifere orignal ramure",
  "🫏": "ane animal bourricot mammifere mule tetu",
  "🐎": "animal cheval course hippique hippodrome tierce",
  "🦄": "animal de licorne licrone tete",
  "🦓": "animal blanc et noir rayure rayures zebre zebrure",
  "🦌": "animal bois cerf",
  "🦬": "animal bison buffle cornes herbivore nature troupeau",
  "🐮": "animal de lait meuh tete vache visage",
  "🐂": "animal astrologie bœuf ferme horoscope taureau zodiaque",
  "🐃": "animal buffle corne zoo",
  "🐄": "animal ferme lait meuh vache",
  "🐷": "animal cochon de ferme porc tete visage",
  "🐖": "animal cochon ferme gros jambon porc truie",
  "🐗": "animal game of sanglier thrones",
  "🐽": "animal cochon de ferme flair groin museau porc sentir tete",
  "🐏": "animal astrologie belier corne ferme horoscope mouton zodiaque",
  "🐑": "animal beler brebis doux ferme laine lait mouton",
  "🐐": "animal astrologie capricorne chevre ferme fromage horoscope lait zodiaque",
  "🐪": "animal bosse desert dromadaire une",
  "🐫": "animal bosse bosses chameau desert deux",
  "🦙": "alpaca alpaga animal guanaco laine lama llama perou vicuna vigogne",
  "🦒": "animal cou girafe taches",
  "🐘": "animal elephant pachyderme trompe",
  "🦣": "animal defenses extinction geant grand laineux mammouth",
  "🦏": "animal corne rhinoceros",
  "🦛": "animal hippo hippopotame",
  "🐭": "animal de souris tete visage",
  "🐁": "animal souris",
  "🐀": "animal rat",
  "🐹": "animal de domestique hamster tete visage",
  "🐰": "animal de dents domestique lapin tete",
  "🐇": "animal domestique lapin",
  "🐿️": "animal ecureuil noisettes",
  "🦫": "animal barrage castor dents rongeur",
  "🦔": "animal epines epineux herisson piquant porc-epic",
  "🦇": "animal chauve-souris vampire",
  "🐻‍❄️": "arctique blanc ours polaire",
  "🐨": "animal australie koala",
  "🐼": "animal de panda tete visage",
  "🦥": "ai animal endormi lent paresseux",
  "🦦": "animal joueur loutre mignon pecheur",
  "🦨": "animal mouffette odeur puer putois",
  "🦘": "austalie joey kangoo kangourou marsupial marsupiaux saut",
  "🦡": "animal blaireau ratel",
  "🐾": "de d’animaux empreintes pattes",
  "🦃": "action animal de dinde dindon graces oiseau thanksgiving volaille",
  "🐔": "animal coq ferme oiseau poule poulet volaille",
  "🐓": "animal coq oiseau volaille",
  "🐣": "animal bebe eclosion eclot naissance naitre nouveau-ne oiseau poussin qui œuf",
  "🐤": "animal de oiseau poussin tete",
  "🐥": "animal bebe de face nouveau-ne oiseau poussin",
  "🐦": "animal oiseau ornithologie",
  "🐧": "animal antarctique banquise manchot oiseau pingouin",
  "🕊️": "animal colombe oiseau paix rameau voler",
  "🦅": "aigle animal oiseau rapace",
  "🦆": "animal canard coin-coin oiseau",
  "🦢": "animal canard cygne jeune oiseau petit vilain",
  "🦉": "animal chouette hibou oiseau sage",
  "🦤": "animal dodo dronte espece eteinte extinction grand maurice oiseau",
  "🪶": "ecrire ecrivain leger oiseau plumage plume voler",
  "🦩": "animal flamant oiseau rose tropical",
  "🦚": "animal bel colore fier fiere oiseau paon paonne pretentieux",
  "🦜": "animal oiseau parle perroquet pirate repete",
  "🪽": "aile angelique aviation celeste mythologie oiseau s’elever s’envoler voler",
  "🐦‍⬛": "animal bec corbeau corneille corvide croasser merle noir oiseau",
  "🪿": "animal bete cacarder canard jars oie oiseau troupeau volaille volee",
  "🐦‍🔥": "ailes cendres feu gloire immortel mythologie oiseau phenix renaissance renaitre revivre transformation",
  "🐸": "animal crapaud de grenouille tete",
  "🐊": "alligator animal caiman crocodile reptile zoo",
  "🐢": "animal carapace lentement reptile tortue",
  "🦎": "animal lezard reptile",
  "🐍": "animal reptile serpent sonnette venin",
  "🐲": "animal de dragon mythe tete tradition",
  "🐉": "animal chine chinois dragon game mythe of thrones tradition",
  "🦕": "animal brachiosaure brontosaure dinosaure diplodocus sauropode",
  "🦖": "animal dinosaure rex t-rex t. tyrannosaure tyrannosaurus",
  "🐳": "animal avec baleine event mer ocean par plage son soufflant souffle",
  "🐋": "animal baleine mer ocean plage",
  "🐬": "animal dauphin flipper mer ocean plage",
  "🦭": "animal de lion mer ocean otarie phoque",
  "🐟": "alimentation animal astrologie horoscope manger nourriture poisson poissons repas zodiaque",
  "🐠": "animal poisson tropical",
  "🐡": "animal poisson poisson-lune",
  "🦈": "animal de dents la mer poisson requin",
  "🐙": "animal creature mer mollusque ocean pieuvre poulpe",
  "🐚": "animal conque coquillage coquille en mer plage spirale",
  "🪸": "climatique corail ocean rechauffement recif",
  "🪼": "aie animal aquarium brulure gelatineux invertebre marin marine meduse mer mou ocean piqure plancton tentacules vie",
  "🐌": "animal escargot jardin lentement nature",
  "🦋": "animal insecte mignon papillon printemps",
  "🐛": "animal chenille insecte jardin",
  "🐜": "animal fourmi insecte jardin",
  "🐝": "abeille animal bourdon guepe insecte miel nature printemps",
  "🪲": "animal insecte scarabee",
  "🐞": "animal bete coccinelle insecte jardin nature",
  "🦗": "animal criquet insecte sauterelle",
  "🪳": "animal blatte cafard coquerelle insecte nuisible",
  "🕷️": "animal araignee insecte",
  "🕸️": "araignee d’araignee toile",
  "🦂": "animal astrologie desert horoscope scorpion zodiaque",
  "🦟": "fievre infection insecte maladie malaria moustique piqure virus",
  "🪰": "animal asticot insecte maladie mouche nuisible pourrissement puanteur putrefaction tse-tse",
  "🪱": "animal annelide de insecte lombric parasite terre ver",
  "🦠": "amibe bacterie biologie microbe microorganisme phagocytose pseudopode science virus",
  "💐": "amoureux anniversaire bouquet fleur fleurs plante rendez-vous roses",
  "🌸": "bourgeon cerisier de fleur plante printemps",
  "💮": "blanche fleur",
  "🪷": "beaute bouddhisme calme fleur hindouisme lotus purete serenite",
  "🏵️": "plante rosette",
  "🌹": "amour beaute fleur plante rose rouge saint-valentin",
  "🥀": "fanee fleur mort rose",
  "🌺": "fleur hibiscus plante",
  "🌻": "champs fleur plante soleil tournesol",
  "🌼": "bourgeon bouton dent-de-lion d’or fleur pissenlit plante printemps",
  "🌷": "bourgeon fleur plante printemps tulipe",
  "🪻": "fleur fleurir indigo jacinthe lavande lilas lupin mauve muflier plante printemps violet",
  "🌱": "germe jeune plant plante plantule pousse pousser printemps semis",
  "🪴": "decoration en ennuyeux faire interieur nature plante pot pousser prendre soin",
  "🌲": "arbre conifere de feuilles foret noel persistantes pin plante sapin",
  "🌳": "arbre caduques feuilles feuillu foret nature plante",
  "🌴": "arbre cocotier palmier plage plante tropical tropiques",
  "🌵": "cactus desert epines nature piquant plante secheresse",
  "🌾": "de grain plant plante riz",
  "🌿": "arbre feuille feuilles plante",
  "☘️": "irlande plante trefle",
  "🍀": "chance feuilles irlande plante porte-bonheur quatre trefle",
  "🍁": "automne d’erable erable feuille morte tomber",
  "🍂": "automne feuille feuilles morte mortes tomber",
  "🍃": "bourrasque de feuille feuilles souffle tourbillon vent virevoltante virevolter",
  "🪹": "branches faire maison nid son vide",
  "🪺": "avec branches faire nid oiseau son œufs",
  "🍄": "champignon mario plante veneneux",
  "🍔": "burger cheeseburger fast food hamburger nourriture",
  "🍇": "fruit nourriture raisin",
  "🍈": "fruit melon",
  "🍉": "fruit pasteque",
  "🍊": "agrume clementine fruit mandarine nourriture orange vitamine",
  "🍋": "acide agrume citron fruit nourriture zeste",
  "🍋‍🟩": "acide agrume citron fruit lime mojito tropical vert zeste",
  "🍌": "banane fruit nourriture potassium",
  "🍍": "ananas fruit nourriture tropical",
  "🥭": "fruit mangue nourriture tropical tropique",
  "🍎": "fruit nourriture pomme rouge",
  "🍏": "fruit nourriture pomme verte",
  "🍐": "fruit nourriture poire",
  "🍑": "fruit nourriture peche",
  "🍒": "cerise cerises fruit nourriture",
  "🍓": "fraise fruit nourriture",
  "🫐": "airelles baies bleu bleuets fruit myrtilles nourriture violet",
  "🥝": "fruit kiwi nourriture",
  "🍅": "fruit legume nourriture plante tomate",
  "🫒": "aliment aperitif apero nourriture olive olivier rameau",
  "🥥": "coco colada de fruit noix nourriture palmier pina",
  "🥑": "avocat fruit nourriture",
  "🍆": "aubergine legume nourriture",
  "🥔": "de legume nourriture patate pomme puree terre",
  "🥕": "carotte legume nourriture",
  "🌽": "de epi ferme mais nourriture",
  "🌶️": "nourriture piment piquant rouge",
  "🫑": "legume piment poivron rouge vert",
  "🥒": "concombre cornichon legume nourriture",
  "🥬": "bok chinois chou choy feuilles frise kale laitue legume pomme salade vertes",
  "🥦": "broccoli brocoli chou legume sauvage",
  "🧄": "ail aromate assaisonnement condiment legume vampire",
  "🧅": "assaisonnement condiment legume ognon oignon",
  "🥜": "arachide cacahuete cacahuetes noisette nourriture",
  "🫘": "haricot haricots legume legumineuse nourriture petit rognon rouge",
  "🌰": "chataigne marron nourriture plante",
  "🫚": "biere de epice gingembre naturel racine sante",
  "🫛": "cosse de edamame feve haricot legume legumineuse petits pois soja",
  "🍄‍🟫": "automne brun cepe champignon fongus marron nature nourriture",
  "🍞": "de miche mie nourriture pain",
  "🥐": "croissant nourriture pain petit-dejeuner viennoiserie",
  "🥖": "baguette nourriture pain",
  "🫓": "arepa galette gordita lavash naan nourriture pain pita plat",
  "🥨": "bretzel nourriture torsade",
  "🥯": "bagel boulangerie petit-dejeuner sandwich schmear",
  "🥞": "crepe gouter nourriture pancake pancakes petit-dejeuner",
  "🧇": "brunch dejeuner gaufre gourmandise gouter moule patisserie petit petit-dejeuner",
  "🧀": "de fromage nourriture part",
  "🍖": "nourriture os sur un viande",
  "🍗": "cuisse de dinde nourriture os poulet volaille",
  "🥩": "cotelette de d’agneau morceau nourriture porc rouge steak viande",
  "🥓": "bacon lard nourriture porc viande",
  "🍟": "fast food frites potatoes potatœs",
  "🍕": "fromage nourriture part pepperoni pizza tranche",
  "🌭": "de dog francfort hot nourriture saucisse",
  "🥪": "de mie nourriture pain pique-nique sandwich",
  "🌮": "mexicain nourriture taco",
  "🌯": "burrito kebab mexicain wrap",
  "🫔": "mexicain nourriture pamonha papillote tamal",
  "🥙": "falafel kebab nourriture pain pita",
  "🧆": "boulette boulettes chiches falafel falafels pois seitan soja viande",
  "🥚": "nourriture œuf",
  "🍳": "au cuire cuisine faire frire friture nourriture petit-dejeuner plat poele se un œuf",
  "🥘": "casserole espagne mitonne paella plat poele riz",
  "🍲": "marmite nourriture ragout",
  "🫕": "bourguignonne chocolat fondue fromage plat poelon savoyarde ski suisse",
  "🥣": "avec bol cereales congee cuillere dejeuner petit soupe une",
  "🥗": "nourriture salade verte",
  "🍿": "cinema nourriture pop-corn",
  "🧈": "beurre gras laitier produit",
  "🧂": "condiment sale saliere saveur sel",
  "🥫": "aliments boite conserve de en nourriture",
  "🍱": "bento boite dejeuner nourriture",
  "🍘": "cracker de galette nourriture riz",
  "🍙": "boulette de japonais nourriture onigiri plat riz",
  "🍚": "bol de nourriture riz",
  "🍛": "au curry nourriture riz",
  "🍜": "bol fumant nouilles nourriture ramen vapeur",
  "🍝": "bolognaise italien nourriture pates restaurant sauce spaghetti",
  "🍠": "au douce four nourriture patate",
  "🍢": "brochette de fruits mer nourriture poisson restaurant",
  "🍣": "japonais nourriture poisson riz sushi",
  "🍤": "beignet crevette de",
  "🍥": "croquette de gateau narutomaki nourriture poisson restaurant surimi",
  "🥮": "automne cake de festival gateau lune moon yuebing",
  "🍡": "bonbons brochette dango de dessert japonais nourriture",
  "🥟": "boulette de dumpling empanada gyoza jiaozi pate pierogi potsticker ravioli",
  "🥠": "biscuit chinois nourriture prophetie",
  "🥡": "baguettes boite carton chinois emporter nourriture",
  "🦀": "animal astrologie cancer crabe horoscope mer pinces plage zodiaque",
  "🦞": "animal bisque de fruit fruits homard mer pinces",
  "🦐": "aliment crevette crustace de fruits mer nourriture",
  "🦑": "aliment animal calamar encornet mollusque nourriture",
  "🦪": "coquillage coquille huitre mollusque perle",
  "🍦": "cornet de dessert glace italienne nourriture sucre",
  "🍧": "coupe creme de dessert glace glacee granite nourriture restaurant sucre",
  "🍨": "coupe creme de dessert glace glacee nourriture restaurant sucre",
  "🍩": "dessert donut doughnut gouter nourriture sucre sucrerie",
  "🍪": "biscuit chocolat cookie de dessert gateau gouter nourriture pepites sucre",
  "🎂": "anniversaire bougies dessert d’anniversaire fete gateau gouter joyeux nourriture patisserie",
  "🍰": "dessert gateau gouter nourriture patisserie sable sucre",
  "🧁": "cupcake dessert muffin patisserie sucre sucrerie",
  "🥧": "aux decoration fruits garniture gateau nourriture pate patisserie tarte tourte",
  "🍫": "barre chocolat chocolatee dessert gouter nourriture sucre",
  "🍬": "bonbon dessert gouter nourriture sucre sucrerie",
  "🍭": "dessert gouter nourriture sucette sucre sucrerie",
  "🍮": "creme dessert flan nourriture pudding renversee sucre",
  "🍯": "de miel nourriture ours pot sucre",
  "🍼": "bebe biberon boisson lait naissance nouveau-ne tetine",
  "🥛": "boisson de lait verre",
  "☕": "boisson cafe cafeine chaude matin the",
  "🫖": "boisson chaude infusion the theiere",
  "🍵": "anse boisson de sans tasse the",
  "🍶": "boisson bouteille et restaurant sake verre",
  "🍾": "alcool boisson bouchon bouteille champagne de felicitations fete pop",
  "🍷": "alcool bar boisson club de restaurant verre vin",
  "🍸": "alcool bar boisson club cocktail martini pied verre",
  "🍹": "alcool bar boite cocktail fete sunrise tequila tropical verre",
  "🍺": "alcool bar biere boisson chope de oktoberfest picoler pinte sante",
  "🍻": "alcool biere boisson chopes de sante tchin trinquer",
  "🥂": "alcool celebrer champagne feter sante tchin trinquer verre verres",
  "🥃": "alcool liqueur tumbler verre whisky",
  "🫗": "accident boisson eau liquide oups renverser un verre verser vider",
  "🥤": "avec boisson de eau fruit fruits gobelet jus paille soda une verre",
  "🧋": "aux boba boisson bubble bulle bulles froid lait paille perle perles tea the zenzou",
  "🧃": "boisson briquette carton de fruits jus paille",
  "🧉": "boisson mate",
  "🧊": "cube froid glace glacon iceberg",
  "🥢": "baguettes hashi",
  "🍽️": "assiette avec couteau couverts cuisine et fourchette restaurant table",
  "🍴": "couteau couverts et faim fourchette manger nourriture repas restaurant",
  "🥄": "couvert cuillere manger",
  "🔪": "arme chef couteau cuisine de outil",
  "🫙": "bocal condiments conserver pot recipient rien sauce vide",
  "🏺": "amphore astrologie cuisine grec grece horoscope vase verseau zodiaque",
  "✈️": "avion de en jet moyen transport vehicule vol voyage",
  "🌍": "afrique espace et europe globe l’afrique l’europe monde planete presentant sur terre tourne",
  "🌎": "amerique ameriques espace globe les l’amerique monde planete presentant sur terre tourne",
  "🌏": "asie australie espace et globe l’asie l’australie monde planete presentant sur terre tourne",
  "🌐": "avec globe internet meridiens monde net terrestre toile",
  "🗺️": "carte du monde planisphere voyage",
  "🗾": "carte du japon voyage",
  "🧭": "boussole compas direction magnetique navigation orientation",
  "🏔️": "enneigee froid montagne neige sommet voyage",
  "⛰️": "montagne nature sommet voyage",
  "🌋": "eruption lave nature volcan",
  "🗻": "fuji mont montagne nature sommet voyage",
  "🏕️": "avec camping nature sapin tente un voyage",
  "🏖️": "avec parasol plage voyage",
  "🏜️": "desert voyage",
  "🏝️": "cocotier deserte ile palmier voyage",
  "🏞️": "national nature parc voyage",
  "🏟️": "stade",
  "🏛️": "classique colonnes monument voyage",
  "🏗️": "batiment chantier construction d’un grue",
  "🧱": "3/4 argile brique briques de mortier mur the voie wall",
  "🪨": "caillou dur lourd pierre roc roche rocher solide",
  "🪵": "arbre bois buche bucheron rondins tronc",
  "🛖": "abri case hutte maison maisonnette yourte",
  "🏘️": "batiment batiments maison maisons pavillons",
  "🏚️": "abandonnee maison",
  "🏠": "batiment foyer maison pavillon residentiel simple",
  "🏡": "avec foyer jardin maison pavillon residentiel",
  "🏢": "bureaux de immeuble ville",
  "🏣": "batiment bureau de japon japonais japonaise poste voyage",
  "🏤": "batiment bureau de europeen poste",
  "🏥": "batiment docteur hopital medecin urgences",
  "🏦": "banque batiment",
  "🏨": "batiment hotel voyage",
  "🏩": "amour batiment cœur hotel love voyage",
  "🏪": "24h/24 batiment epicerie magasin superette supermarche",
  "🏫": "batiment ecole",
  "🏬": "batiment centre commercial grand magasin",
  "🏭": "batiment usine",
  "🏯": "batiment chateau japonais voyage",
  "🏰": "batiment chateau europeen voyage",
  "💒": "amour chapelle cœur eglise mariage",
  "🗼": "de japon tokyo tour voyage",
  "🗽": "de la liberte new statue voyage york",
  "⛪": "batiment chapelle chretien croix eglise religion voyage",
  "🕌": "islam mosquee musulman musulmane religion voyage",
  "🛕": "bouddhisme bouddhiste hindou pagode religion stupa temple",
  "🕍": "judaisme juif juive religion synagogue temple voyage",
  "⛩️": "religion sanctuaire shinto voyage",
  "🕋": "islam kaaba musulman musulmane religion voyage",
  "⛲": "eau fontaine",
  "⛺": "camping nature tente voyage",
  "🌁": "brouillard brume voyage",
  "🌃": "etoilee etoiles nuit ville voyage",
  "🏙️": "batiment ville voyage",
  "🌄": "de derriere les levant lever matin montagnes nature soleil voyage",
  "🌅": "de levant lever matin nature soleil voyage",
  "🌆": "au coucher crepuscule de immeubles la nuit soir soleil tombee ville voyage",
  "🌇": "coucher crepuscule de en la nuit soir soleil tombee ville voyage",
  "🌉": "de nuit pont",
  "♨️": "chaud chaudes source sources vapeur",
  "🎠": "cheval de manege",
  "🛝": "aire de glissade jeu jouer toboggan",
  "🎡": "attractions d’attractions grande parc roue",
  "🎢": "attractions d’attractions montagnes parc russes",
  "💈": "barbier coiffeur coiffure de enseigne salon",
  "🎪": "chapiteau cirque",
  "🚂": "chemin de fer locomotive machine moyen rail tchou train transport vapeur voyage",
  "🚃": "chemin de fer moyen rail train tram tramway transport voiture voyage wagon",
  "🚄": "chemin de fer grande moyen rail rapide tgv train transport vitesse voyage",
  "🚅": "chemin de fer grande moyen rail rapide tgv train transport vitesse voyage",
  "🚆": "arrivee chemin de fer moyen rail train transport voyage",
  "🚇": "de metro moyen transport",
  "🚈": "de leger metro monorail moyen rail rer transport",
  "🚉": "chemin de fer gare moyen rail rer train transport",
  "🚊": "de moyen rer tram tramway transport trolley trolleybus",
  "🚝": "de monorail moyen transport vehicule",
  "🚞": "chemin de fer montagne moyen rail train transport voyage wagon",
  "🚋": "de moyen tram tramway transport trolleybus voiture voyage wagon",
  "🚌": "bus de ecole moyen transport vehicule",
  "🚍": "arrive bus car de face moyen qui transport",
  "🚎": "bus de moyen tram tramway transport trolley trolleybus",
  "🚐": "bus de minibus moyen navette transport vehicule",
  "🚑": "ambulance urgences vehicule",
  "🚒": "camion de pin-pon pompier",
  "🚓": "de flic patrouille police vehicule voiture",
  "🚔": "arrive de face police qui vehicule voiture",
  "🚕": "de jaune moyen taxi transport uber vehicule",
  "🚖": "de face jaune joe le new taxi uber voiture york",
  "🚗": "automobile conduire de moyen transport vehicule voiture voyage",
  "🚘": "arrive automobile conduire de face moyen qui transport vehicule voiture voyage",
  "🚙": "automobile conduire de loisirs moyen sport transport utilitaire vehicule voiture voyage",
  "🛻": "auto benne camion camionnette lourd pick-up pickup plateau poids transports vehicule",
  "🚚": "camion camionnette de livraison moyen transport vehicule",
  "🚛": "camion de lourd moyen poids semi semi-remorque transport vehicule",
  "🚜": "de moyen tracteur transport vehicule",
  "🏎️": "automobile course de formule voiture",
  "🏍️": "course moto",
  "🛵": "scooter",
  "🦽": "accessibilite fauteuil handicap manuel roulant",
  "🦼": "accessibilite fauteuil handicap motorise roulant",
  "🛺": "rickshaw taxi thai tricycle tuk",
  "🚲": "bicyclette cyclisme de moyen transport velo voyage",
  "🛴": "trottinette",
  "🛹": "glisse longboard planche roulettes skate skateboard",
  "🛼": "derby patin roller roulette roulettes sport",
  "🚏": "arret bus de",
  "🛣️": "autoroute route voyage",
  "🛤️": "chemin de fer ferree rail train voie voyage",
  "🛢️": "baril de petrole",
  "⛽": "diesel essence gazole pompe station",
  "🛞": "cercle pneu roue tourner vehicule voiture",
  "🚨": "alarme alerte gyrophare lumiere police sirene urgences voiture",
  "🚥": "carrefour circulation croisement de feu horizontal tricolore",
  "🚦": "carrefour circulation croisement de feu tricolore vertical",
  "🛑": "octogonal panneau signe stop",
  "🚧": "barriere travaux",
  "⚓": "ancre bateau outil voyage",
  "🛟": "bouee de flotter sauver sauvetage sauveteur secours securite",
  "⛵": "bateau de mer moyen plaisance transport voilier voyage yacht",
  "🛶": "bateau canoe rame ramer",
  "🚤": "bateau de ete hors-bord luxe moyen transport vedette voyage",
  "🛳️": "bateau croisiere paquebot voyage",
  "⛴️": "bateau de ferry moyen transport voyage",
  "🛥️": "bateau moteur",
  "🚢": "bateau croisiere de moyen navire paquebot titanic transport voyage",
  "🛩️": "avion de moyen petit transport voyage",
  "🛫": "au avion de decollage depart moyen transport voyage",
  "🛬": "arrivee atterrissage avion de l’atterrissage moyen transport voyage",
  "🪂": "ascensionnel chute fortes libre parachute parapente sensations",
  "💺": "chaise fauteuil place siege",
  "🚁": "de helico helicoptere moyen transport vehicule",
  "🚟": "de moyen suspendu train transport voyage",
  "🚠": "de montagne moyen ski telecabine telepherique transport",
  "🚡": "aerien de moyen telecabine tramway transport",
  "🛰️": "espace satellite",
  "🚀": "de decollage espace fusee moyen transport voyage",
  "🛸": "alien extraterrestre ovni soucoupe volante",
  "🛎️": "cloche clochette comptoir de hotel reception sonnette",
  "🧳": "bagage valise voyage",
  "⌛": "chronometre minuteur sable sablier temps",
  "⏳": "attendre avec chronometre coule minuteur qui sable sablier temps",
  "⌚": "heure montre",
  "⏰": "alarme attendre dring heure matin retard reveil sonnerie",
  "⏱️": "chronometre heure temps",
  "⏲️": "heure horloge minuteur temps",
  "🕰️": "horloge pendule posee",
  "🕛": "12 heure horloge midi midi/minuit minuit pile",
  "🕧": "00 12 30 demi demie et heure horloge midi midi/minuit minuit",
  "🕐": "13 heure heures horloge treize une",
  "🕜": "13 30 demie et heure heures horloge treize trente une",
  "🕑": "14 deux heure heures horloge quatorze",
  "🕝": "14 30 demie deux et heure heures horloge quatorze trente",
  "🕒": "15 heure heures horloge quinze trois",
  "🕞": "15 30 demie et heure heures horloge quinze trente trois",
  "🕓": "16 heures quatre seize",
  "🕟": "16 30 demie et heure heures horloge quatre seize trente",
  "🕔": "17 cinq dix-sept heure heures horloge",
  "🕠": "17 30 cinq demie dix-sept et heure heures horloge trente",
  "🕕": "18 dix-huit heure heures horloge six",
  "🕡": "18 30 demie dix-huit et heure heures horloge six trente",
  "🕖": "19 dix-neuf heure heures horloge sept",
  "🕢": "19 30 demie dix-neuf et heure heures horloge sept trente",
  "🕗": "20 heure heures horloge huit vingt",
  "🕣": "20 30 demie et heure heures horloge huit trente vingt",
  "🕘": "21 heures neuf",
  "🕤": "21 30 demie et heure heures horloge neuf trente une vingt",
  "🕙": "10 22 dix heure heures horloge vingt-deux",
  "🕥": "10 22 30 demie dix et heure heures horloge trente vingt-deux",
  "🕚": "11 23 heure heures horloge onze vingt-trois",
  "🕦": "11 23 30 demie et heure heures horloge onze trente vingt-trois",
  "🌑": "espace lune nouvelle sombre",
  "🌒": "croissante espace lune nuit",
  "🌓": "de espace lune nuit premier quartier",
  "🌔": "croissant croissante espace gibbeuse gibbeux lune nuit",
  "🌕": "espace lune nuit pleine",
  "🌖": "decroissant decroissante espace gibbeuse gibbeux lune nuit",
  "🌗": "de dernier espace lune quartier",
  "🌘": "croissant de decroissante descendante espace lune nuit",
  "🌙": "croissant de espace lune nuit ramadan",
  "🌚": "avec espace lune nouvelle nuit visage",
  "🌛": "avec croissant de espace lune nuit premier quartier visage",
  "🌜": "avec croissant de dernier lune nuit quartier visage",
  "🌡️": "meteo thermometre",
  "☀️": "beau brillant espace grand meteo rayons soleil temps",
  "🌝": "avec lune nuit pleine sourire visage",
  "🌞": "avec chaleur chaud de eclatant ensoleille jour lumiere meteo plage rayon soleil visage",
  "🪐": "anneaux planete saturne saturnien saturnienne",
  "⭐": "astronomie etoile nuit",
  "🌟": "brillante eclat etincelant etincelle etoile etoilee nuit succes",
  "🌠": "espace etoile filante nuit",
  "🌌": "espace lactee voie",
  "☁️": "gris meteo nuage",
  "⛅": "cache derriere les meteo nuage nuages nuageux soleil",
  "⛈️": "avec eclair et meteo nuage orage pluie",
  "🌤️": "cache derriere meteo nuage petit soleil un",
  "🌥️": "cache derriere gros meteo nuage soleil un",
  "🌦️": "cache de derriere gouttes meteo nuage pluie soleil un",
  "🌧️": "avec averse de gouttes mauvais meteo nuage pluie temps",
  "🌨️": "avec de flocons froid hiver meteo neige nuage",
  "🌩️": "avec eclair nuage orage orageux temps un",
  "🌪️": "cyclone meteo nuage tornade tourbillon",
  "🌫️": "brouillard brume fog meteo nuage",
  "🌬️": "avec du meteo nuage souffle vent visage",
  "🌀": "cyclone spirale tourbillon typhon vertige",
  "🌈": "arc-en-ciel bisexuelle gay homosexuelle lesbienne lgbtqia meteo nature pluie pride transgenre",
  "🌂": "ferme meteo parapluie pluie",
  "☂️": "ouvert parapluie pluie",
  "☔": "avec de gouttes meteo parapluie pluie",
  "⛱️": "au le meteo parapluie parasol plage pluie sol soleil sur voyage",
  "⚡": "courant danger eclair electricite haute nature orage symbole tension vitesse",
  "❄️": "de flocon froid meteo neige",
  "☃️": "avec bonhomme de flocons neige",
  "⛄": "bonhomme de flocons froid neige sans",
  "☄️": "comete espace meteore",
  "🔥": "allumer bruler chaud feu flamme fournaise incendie",
  "💧": "bd d’eau eau froid froides goutte larme meteo nature pluie sueurs tristesse",
  "🌊": "eau kanagawa lame large maree mer nature ocean remous rouleau surf vague",
  "⚽": "balle ballon de football sport",
  "🎃": "citrouille halloween lanterne",
  "🎄": "arbre de fete fetes guirlandes noel sapin",
  "🎆": "14 artifice d’artifice fete feu juillet",
  "🎇": "14 artifice cierge d’artifice etincelle etincelles fete feu juillet magique",
  "🧨": "dynamite d’artifice etincelle explosif explosive feu petard tnt",
  "✨": "etincelles etoile etoilee etoiles magie nuit scintiller",
  "🎈": "anniversaire ballon baudruche de fete gonflable",
  "🎉": "anniversaire cotillons fete super",
  "🎊": "anniversaire confettis fete",
  "🎋": "arbre fete japon prieres tanabata vœux",
  "🎍": "bambou decoratif fete japonais plante",
  "🎎": "festival japon japonaises poupees",
  "🎏": "carpe fete koinobori",
  "🎐": "carillon clochette eolien fete vent",
  "🎑": "ceremonie de la lune",
  "🧧": "argent bonne cadeau chance enveloppe hongbao lai rouge see",
  "🎀": "fete nœud rose ruban",
  "🎁": "anniversaire cadeau emballe fete noel nœud surprise",
  "🎗️": "de memoire ruban souvenir",
  "🎟️": "billet d’entree place spectacle",
  "🎫": "billet place spectacle",
  "🎖️": "medaille militaire",
  "🏆": "champion championne coupe gagner prix trophee victoire",
  "🏅": "champion championne d’or medaille sport sportive vainqueur victoire",
  "🥇": "1er d’or medaille or premier",
  "🥈": "2e argent deuxieme d’argent medaille",
  "🥉": "3e bronze de medaille troisieme",
  "⚾": "balle baseball de sport",
  "🥎": "balle gant softball sports",
  "🏀": "ballon basket basket-ball panier sport",
  "🏐": "ballon jeu match sport volley volley-ball",
  "🏈": "americain ballon bowl football sport super",
  "🏉": "ballon rugby sport",
  "🎾": "balle de sport tennis",
  "🥏": "discoplane disque disque-volant frisbee sport ultimate ultime-passe volant",
  "🎳": "boule bowling jeu partie quilles sport strike",
  "🏏": "balle batte cricket de jeu match sport",
  "🏑": "balle crosse gazon hockey sport sur",
  "🏒": "crosse glace hockey palet sport sur",
  "🥍": "balle but crosse lacrosse raquette sport",
  "🏓": "balle de jeu partie ping-pong raquette sport table tennis",
  "🏸": "badminton jeu match raquette sport volant",
  "🥊": "boxe de gant sport",
  "🥋": "arts d’arts judo karate kimono martiaux sport taekwondo tenue",
  "🥅": "but cage filet sport",
  "⛳": "de drapeau golf sport trou",
  "⛸️": "glace patin patiner patinoire sport",
  "🎣": "canne la ligne peche sport",
  "🤿": "apnee de et masque plongee plonger snorkeling tuba",
  "🎽": "athletisme course de jogging maillot pied running sport tee-shirt",
  "🎿": "neige ski sport",
  "🛷": "glisser luge neige traineau",
  "🥌": "curling de granit jeu match partie pierre sport",
  "🎯": "cible dans flechettes jeu le mille",
  "🪀": "descendre jouet monter osciller yoyo",
  "🪁": "cerf-volant planer voler",
  "🔫": "arme eau feu flingue pistolet revolver",
  "🎱": "billard boule de huit jeu magique pool",
  "🔮": "avenir boule cristal de magie voyant voyante",
  "🪄": "abracadabra baguette de magicien magie magique sorcier sorciere sort tour",
  "🎮": "jeu joystick manette playstation video xbox",
  "🕹️": "de jeu joystick manette video",
  "🎰": "casino jeu machine sous",
  "🎲": "de des hasard jeu",
  "🧩": "assemblage de enigme indice interloque manquante piece puzzle",
  "🧸": "en jeu jouet nounours ours peluche",
  "🪅": "bonbons cinco confiseries de fete mai mayo mexicain pinata",
  "🪩": "boule briller danse disco facettes fete soiree",
  "🪆": "emboite empiler gigogne jouet matriochka poupee poupees russe russes russie",
  "♠️": "carte couleur jeu pique",
  "♥️": "cartes couleur cœur jeu jouer rouge",
  "♦️": "carreau carreaux carte couleur jeu",
  "♣️": "cartes couleur jeu jouer noir trefle",
  "♟️": "duper d’echec echec pion sacrifiable",
  "🃏": "carte cartes jeu joker jouer",
  "🀄": "dragon jeu mah-jong mahjong rouge",
  "🎴": "carte des fleur fleurs japonais jeu jouer",
  "🎭": "acteur actrice art masque spectacle theatre vivant",
  "🖼️": "art avec cadre encadre image musee peinture tableau",
  "🎨": "art artiste couleurs de musee palette peindre peintre peinture",
  "🧵": "aiguille bobine coudre couture de ficelle fil",
  "🪡": "aiguille broderie coudre couture fil points suture tailleur",
  "🧶": "boule crochet fil laine pelote tricot",
  "🪢": "attacher corde entrelacer lien noue nœud tordre",
  "💡": "allumer ampoule bande bd dessin dessinee idee lampe lumiere",
  "👓": "accessoire de lunettes vetements vue yeux œil",
  "🕶️": "de lunettes noires soleil",
  "🥽": "chimiste de des labo lunettes masque natation piscine protection soudage soudure yeux",
  "🥼": "blanc blanche blouse docteur experience experimentation labo laboratoire manteau medecin scientifique vetements",
  "🦺": "chantier de fluo gilet jaune orange securite surete visibilite",
  "👔": "chemise cravate travail vetements",
  "👕": "bleu chemise courses decontracte polo shopping t-shirt tee-shirt vetements week-end",
  "👖": "bleu courses denim jean pantalon shopping vetements week-end",
  "🧣": "cou echarpe foulard froid glagla vetements",
  "🧤": "gant gants main vetements",
  "🧥": "froid glagla manteau veste vetements",
  "🧦": "chaussettes pieds vetements",
  "👗": "courses elegante jolie robe shopping vetements",
  "👘": "kimono vetements",
  "🥻": "inde mode robe sari traditionnel vetement",
  "🩱": "bain de maillot piece une",
  "🩲": "bain de maillot piece slip sous-vetement une",
  "🩳": "baignade bain calecon de maillot piscine plage short sous-vetement",
  "👙": "bain bikini de maillot nager piscine plage vetements",
  "👚": "chemise chemisier courses de femme shopping vetements",
  "🪭": "agiter chaleur charmer chaud danse danser eventail eventer rafraichir timide",
  "👛": "accessoire courses main monnaie porte-monnaie sac shopping vetements",
  "👜": "accessoire courses main sac shopping vetements",
  "👝": "accessoire main pochette sac trousse vetements",
  "🛍️": "achats courses de sac sacs shopping",
  "🎒": "cartable dos ecole sac",
  "🩴": "claquettes de ete mer plage sandales tatanes tong tongs",
  "👞": "accessoire chaussure coup courses de d’homme homme marron pied shopping vetements",
  "👟": "accessoire athletisme basket chaussure coup courir courses de pied shopping sport tennis vetements vite",
  "🥾": "camping chantier chaussure chaussures de marche marron montagne rando randonnee securite timberland vetements",
  "🥿": "ballerine chaussure chaussures lacets mule plate plates sans vetements",
  "👠": "accessoire aiguille chaussure courses de femme haut mode shopping stilletto talon vetements",
  "👡": "chaussure de femme haut sandale talon vetements",
  "🩰": "ballerines ballet chaussons chaussures classique danse de",
  "👢": "accessoire botte chaussure courses de femme shopping vetements",
  "🪮": "afro cheveux demeler demeloir peigne peigner",
  "👑": "accessoire couronne famille monarchie monarque reine roi royale royaute succes vetements",
  "👒": "chapeau de femme vetements",
  "🎩": "accessoire chapeau de elegant forme haut haut-de-forme magie vetements",
  "🎓": "accessoire chapeau diplome etudiant toque universitaire universite vetements",
  "🧢": "americaine baseball cap casquette chapeau de vetements",
  "🪖": "armee casque equipement guerre guerrier militaire protection soldat",
  "⛑️": "assistance blanche casque croix de sauveteur secouriste secours",
  "📿": "accessoire chapelet collier perles priere religion vetements",
  "💄": "cosmetiques levres maquillage rendez-vous rouge",
  "💍": "alliance amour bague brillant diamant etincelant fiancailles mariage solitaire",
  "💎": "argent bijou diamant fiancailles joyau mariage pierre precieuse romantique",
  "🔇": "barre chut d’enceinte enceinte haut-parleur muet silence son sourdine",
  "🔈": "bas des d’enceinte enceinte enceintes faible haut-parleur son volume",
  "🔉": "des d’enceinte enceinte enceintes haut-parleur moyen son volume",
  "🔊": "des d’enceinte eleve enceinte enceintes fort haut-parleur musique son volume",
  "📢": "communication fort haut-parleur megaphone message son",
  "📣": "encourager hourra manifestation megaphone porte-voix",
  "📯": "cor de facteur postal poste",
  "🔔": "cloche clochette sonner",
  "🔕": "alarme barree cloche desactivee silence",
  "🎼": "musique note partition",
  "🎵": "de musique note",
  "🎶": "de musique note notes partition",
  "🎙️": "chant de enregistrement micro microphone musique studio",
  "🎚️": "curseur de musique niveau",
  "🎛️": "boutons commande controle de musique reglage reglages",
  "🎤": "chanter karaoke micro microphone musique",
  "🎧": "casque ecouteur ecouteurs musique son",
  "📻": "actualites communication loisirs musique radio video",
  "🎷": "instrument musique saxophone",
  "🪗": "accordeon bandoneon bretelles concert concertina instrument melodie musique piano",
  "🎸": "electrique guitare instrument musique",
  "🎹": "clavier instrument musique piano touches",
  "🎺": "instrument musique trompette",
  "🎻": "instrument musique violon",
  "🪕": "banjo cordes instrument musique",
  "🥁": "baguette baguettes batterie musique tambour",
  "🪘": "battement conga djembe instrument musique percussions rythme tambour",
  "🪇": "cha danse danser fete hochet instrument maracas musique percussion secouer",
  "🪈": "bec bois fanfare fifre flute flutiste instrument musique orchestre piccolo",
  "📱": "communication portable smartphone telephone",
  "📲": "appel avec communication entrant fleche portable recevoir smartphone telephone un une",
  "☎️": "rouge telephone",
  "📞": "combine communication telephone telephonique",
  "📟": "bip bipeur communication pager",
  "📠": "communication fax telecopieur",
  "🔋": "pile",
  "🪫": "batterie decharge electronique energie faible pile",
  "🔌": "avec branche cable electricite electrique fiche prise",
  "💻": "bureau ordinateur portable travail",
  "🖥️": "bureau de moniteur ordinateur",
  "🖨️": "imprimante imprimer ordinateur",
  "⌨️": "clavier informatique ordinateur",
  "🖱️": "d’ordinateur informatique souris",
  "🖲️": "boule commande de informatique ordinateur souris trackball",
  "💽": "disque d’ordinateur minidisc",
  "💾": "disque disquette informatique ordinateur",
  "💿": "blu-ray cd disque dvd",
  "📀": "blu-ray cd disque dvd",
  "🧮": "abaque boulier calcul calculation math mathematiques",
  "🎥": "camera cinema film filmer realisateur realisatrice video",
  "🎞️": "bande cinema film pellicule",
  "📽️": "cinema cinematographique film projecteur video",
  "🎬": "action ca clap film tourne",
  "📺": "ecran petit tele televiseur television tv",
  "📷": "appareil photo selfie video",
  "📸": "appareil avec flash photo",
  "📹": "camera camescope filmer video",
  "📼": "cassette magnetoscope vhs video videocassette vintage",
  "🔍": "agrandir chercher detective gauche loupe orientee recherche",
  "🔎": "agrandir chercher detective droite loupe orientee recherche",
  "🕯️": "bougie chandelle lumiere",
  "🔦": "electrique lampe lumiere outil torche",
  "🏮": "japonais lampion lanterne lumiere restaurant rouge",
  "🪔": "arti beurre diwali diya fete huile inde lampe",
  "📔": "avec cahier carnet couverture ecole ecrire livre",
  "📕": "apprendre ecole enseignement ferme lire litterature livre manuel rouge savoir scolaire",
  "📖": "apprendre bibliotheque ecole enseignement etudier lecture lire litterature livre manuel ouvert roman savoir scolaire",
  "📗": "apprendre bibliotheque ecole enseignement etudier lecture lire litterature livre manuel savoir scolaire vert",
  "📘": "apprendre bleu ecole education lecture lire litterature livre manuel roman scolaire",
  "📙": "apprendre ecole education lecture lire litterature livre manuel orange roman scolaire",
  "📚": "apprendre bibliotheque ecole enseignement etudier lecture lire litterature livres manuels roman savoir scolaires",
  "📓": "cahier carnet ecrire",
  "📒": "cahier carnet classeur compte de grand livre",
  "📃": "document enroulee page",
  "📜": "papier parchemin",
  "📄": "document page",
  "📰": "actualites communication gros journal presse titres une",
  "🗞️": "actualites journal presse roule",
  "📑": "marque marqueur onglets signet signets",
  "🔖": "marque-page marqueur signet",
  "🏷️": "etiquette",
  "💰": "argent avare banque dollar d’argent parier payer plein sac",
  "🪙": "argent de euro fortune metal monnaie or piece riche sou tresor",
  "💴": "argent banque billet de en payer yens",
  "💵": "argent banque billet de dollar dollars en payer",
  "💶": "argent banque billet de en euros payer",
  "💷": "argent banque billet de en livres payer",
  "💸": "ailes argent avec banque billet de des dollars payer",
  "💳": "argent bancaire banque carte credit de payer",
  "🧾": "caisse compta comptabilite comptable comptes de facture faire justificatif les preuve recu ticket",
  "💹": "avec banque courbe croissance devise en graphique hausse marche monnaie tendance yen",
  "✉️": "courrier e-mail electronique enveloppe lettre message",
  "📧": "courriel courrier e-mail electronique lettre message",
  "📨": "courriel courrier e-mail electronique enveloppe envoyer lettre message recevoir recu",
  "📩": "avec communication courriel courrier e-mail electronique enveloppe envoi envoye envoyer fleche message",
  "📤": "boite courriel courrier d’envoi e-mail electronique envoyer fleche lettre message",
  "📥": "boite courriel courrier de e-mail electronique fleche lettre message reception recevoir",
  "📦": "boite colis livraison paquet",
  "📫": "aux boite courrier drapeau fermee lettres leve",
  "📪": "aux baisse boite courrier drapeau fermee lettres",
  "📬": "aux boite courrier drapeau lettres leve ouverte",
  "📭": "aux baisse boite courrier drapeau lettres ouverte",
  "📮": "aux boite courrier lettres poste",
  "🗳️": "avec bulletin de electorale un urne vote voter",
  "✏️": "crayon gomme mine papier",
  "✒️": "ecrire noir plume stylo",
  "🖋️": "ecrire plume stylo",
  "🖊️": "bille ecrire stylo stylo-bille",
  "🖌️": "peinture pinceau",
  "🖍️": "crayon pastel rouge",
  "📝": "bloc-notes crayon ecrire memo",
  "💼": "accessoire bureau cartable porte-documents",
  "📁": "dossier fichier repertoire",
  "📂": "dossier le ouvert ouvrir repertoire",
  "🗂️": "classement classeur index intercalaire intercalaires",
  "📅": "calendrier date",
  "📆": "agenda calendrier date ephemeride planning",
  "🗒️": "bloc-notes cahier notes spirale spirales",
  "🗓️": "bloc-notes calendrier spirale spirales",
  "📇": "carnet carte d’adresses fiche index rolodex vintage",
  "📈": "croissance donnees en graphique hausse haut tendance",
  "📉": "baisse bas chute donnees en graphique negatif tendance",
  "📊": "barres donnees graphique graphiques",
  "📋": "fournitures liste porte-bloc presse-papiers",
  "📌": "fournitures punaise",
  "📍": "carte emplacement epingle fournitures punaise ronde",
  "📎": "fournitures trombone",
  "🖇️": "fournitures trombones",
  "📏": "fournitures mathematiques plate regle",
  "📐": "equerre fournitures mathematiques",
  "✂️": "ciseaux couper decouper fournitures papier",
  "🗃️": "boite classeur dossier dossiers",
  "🗄️": "classement classer classeur dossier dossiers meuble",
  "🗑️": "corbeille papiers poubelle",
  "🔒": "cadenas ferme prive verrouille verrouiller",
  "🔓": "cadenas deverrouiller ouvert ouvrir",
  "🔏": "avec cadenas confidentiel ferme plume prive stylo un verrouille",
  "🔐": "avec cadenas cle ferme prive securise une verrouille",
  "🔑": "cle de mot ouvrir passe serrure",
  "🗝️": "ancienne cle fermer indice serrure verrouiller",
  "🔨": "marteau outil reparer travaux",
  "🪓": "bois bucheron fendre hache hachette",
  "⛏️": "mine outil pioche",
  "⚒️": "burin et marteau outil outils pioche",
  "🛠️": "cle et marteau molette outil outils",
  "🗡️": "arme couteau dague poignard",
  "⚔️": "arme armes croisees epees",
  "💣": "bande bd bombe boum danger dessin dessinee explosion",
  "🪃": "aborigene australie boomerang jeu outil repercussion retour",
  "🏹": "arc archer astrologie et fleche horoscope l’arc sagittaire sport tir zodiaque",
  "🛡️": "arme bouclier",
  "🪚": "bois egoine outil scie scier",
  "🔧": "cle molette outil travaux",
  "🪛": "outil outillage tournevis vis",
  "🔩": "boulon ecrou et outil travaux vis",
  "⚙️": "dentee engrenage outil roue",
  "🗜️": "compresser comprimer outil serre-joint serre-joints",
  "⚖️": "astrologie balance horoscope justice poids zodiaque",
  "🦯": "accessibilite aveugle blanche canne deficient malvoyant visuel",
  "🔗": "chaine chainons maillons mousqueton",
  "⛓️‍💥": "brisee cassee chaine liberte rompue",
  "⛓️": "chaine chaines",
  "🪝": "accrocher appater attraper capitaine crochet ferrer hamecon hameconner",
  "🧰": "boite caisse coffre mecanique mecano outil outils",
  "🧲": "aimant aimanter attirer attraction cheval fer magnet magnetique negatif positif",
  "🪜": "ascension barreau echelle echelon escabeau grimper monter",
  "⚗️": "alambic chimie outil",
  "🧪": "chimie chimiste essai experience experimentation labo laboratoire reaction science sciences tube",
  "🧫": "bacterie bacteriologie biologie biologiste boite culture de labo laboratoire micro-organismes microbiologie petri science",
  "🧬": "adn biologie biologiste evolution gene genetique science vie",
  "🔬": "experience laboratoire microscope outil science",
  "🔭": "astronomie espace outil planetes science telescope",
  "📡": "antenne parabole parabolique satellite science",
  "💉": "aiguille docteur malade medecine piqure seringue vaccin vaccination",
  "🩸": "de don du goutte medecine menstruation menstruations regles sang",
  "💊": "docteur gelule malade medecine medicament pilule vitamines",
  "🩹": "bandage bobo medecine pansement premiers secours sparadrap",
  "🩼": "accident aide bequille blesse boiter canne handicap",
  "🩺": "cœur diagnostic docteur medecin medecine poumons stethoscope",
  "🩻": "cage docteur medical os radiographie rayons squelette thoracique",
  "🚪": "d’entree placard porte",
  "🛗": "accessibilite ascenseur descente monte-charge monte-personnes montee",
  "🪞": "beaute glace image maquillage miroir psyche reflet",
  "🪟": "air cadre carreaux fenetre frais ouverture transparent vitre vue",
  "🛏️": "dormir hotel lit",
  "🛋️": "avec canape et lampe une",
  "🪑": "assis chaise siege",
  "🚽": "cabinets toilettes wc",
  "🪠": "bouche deboucheur degorgement outil plombier succion toilettes ventouse",
  "🚿": "de douche eau pommeau",
  "🛁": "baignoire bain mousse",
  "🪤": "apat appat fromage leurre piege rat souris tapette",
  "🪒": "coupant lame raser rasoir tranchant",
  "🧴": "apres-shampoing bouteille corps creme de flacon hydratant hydratante le lotion pour shampoing shampooing solaire",
  "🧷": "couche de epingle imperdable lange nourrice punk rock surete",
  "🧹": "balai balais balayage menage nettoie nettoyage nettoye nettoyer sorciere",
  "🧺": "agriculture cueillette lessive linge panier pique-nique",
  "🧻": "de essuie-tout hygienique papier pq rouleau toilette",
  "🪣": "conteneur plage seau",
  "🧼": "bain bulles de lavage lave laver me mousse pain porte-savon savon se",
  "🫧": "bulle bulles l’eau propre savon sous",
  "🪥": "bain brosse brosser de dentaire dents hygiene laver les salle",
  "🧽": "absorbante absorbe eponge laver nettoyage nettoyer poreuse savonner",
  "🧯": "chaud eteindre extincteur feu fire incendie",
  "🛒": "caddie chariot courses panier shopping supermarche",
  "🚬": "allumee cigarette fumer fumeur signe",
  "⚰️": "cercueil enterrement mort obseques vampire",
  "🪦": "cimetiere enterrement funerailles memorial mort pierre rip sepulture stele tombale tombe",
  "⚱️": "cendres funeraire mort obseques urne",
  "🧿": "amulette bleu boncuk l’oeil mauvais nazar nazarboncuk oeil perle superstition talisman turc œil",
  "🪬": "amulette chance de fatma hamsa khamsa main myriam protection",
  "🗿": "de ile moai monolithe paques statue voyage",
  "🪧": "affiche ecriteau greve manifestation pancarte panneau protestation signe",
  "🪪": "carte conduire de d’identite justificatif papiers permis piece securite",
  "🏧": "argent automatique automatiques banque billets dab de distributeur guichet retrait",
  "🚮": "corbeille dechets icone jeter poubelle",
  "🚰": "du eau potable robinet",
  "♿": "acces fauteuil handicapes mobilite reduite roulant symbole",
  "🚹": "homme hommes symbole toilettes wc",
  "🚺": "femme femmes symbole toilettes wc",
  "🚻": "panneau toilettes wc",
  "🚼": "bebe change de espace symbole",
  "🚾": "toilettes wc",
  "🛂": "controle des passeport passeports",
  "🛃": "douane douanes",
  "🛄": "aeroport arrivee avion bagages des retrait valise voyage",
  "🛅": "bagages casier cle consigne valise",
  "⚠️": "attention avertissement d’avertissement symbole",
  "🚸": "circulation d’enfants ecole enfants pietons traversee",
  "⛔": "circulation entree interdiction interdit interdite non panneau sens",
  "🚫": "d’interdiction entree interdiction interdit interdite symbole",
  "🚳": "bicyclette interdiction interdit interdits velo velos",
  "🚭": "barree cigarette de fumer interdiction interdit",
  "🚯": "dechets depot d’ordures interdiction interdit jeter ne pas",
  "🚱": "boire eau imbuvable interdiction interdit ne non pas potable",
  "🚷": "aux interdiction interdit pietons",
  "📵": "interdiction interdit interdits portable portables telephone telephones",
  "🔞": "18 ans aux de dix-huit d’age et interdiction interdit limite majorite mineur mineurs moins plus",
  "☢️": "radioactif radioactivite symbole",
  "☣️": "biologique danger symbole",
  "⬆️": "direction fleche haut nord sens",
  "↗️": "direction droite fleche haut nord-est sens",
  "➡️": "direction droite est fleche sens",
  "↘️": "bas direction droite fleche sens sud-est",
  "⬇️": "bas direction fleche sens sud",
  "↙️": "bas direction fleche gauche sens sud-ouest",
  "⬅️": "direction fleche gauche ouest sens",
  "↖️": "direction fleche gauche haut nord-ouest sens",
  "↕️": "bas dans deux fleche haut les sens",
  "↔️": "droite fleche gauche",
  "↩️": "courbe fleche gauche",
  "↪️": "courbe droite fleche",
  "🔃": "actualiser aiguilles dans des d’une fleche fleches horaire le montre recharger sens symbole",
  "🔄": "actualiser aiguilles antihoraire contraire dans des d’une fleche fleches horaire inverse le montre retour sens",
  "🔙": "fleche gauche la retour vers",
  "🔚": "fin fleche gauche la vers",
  "🔛": "active dans deux droite et fleche gauche les sens",
  "🔜": "bientot fleche",
  "🔝": "en fleche haut le vers",
  "🛐": "culte de lieu prier religion",
  "⚛️": "athee atome de l’atome symbole",
  "🕉️": "hindou om religion",
  "✡️": "david de etoile judaisme juif juive religion",
  "☸️": "bouddhisme bouddhiste de dharma du religion roue",
  "☯️": "complementaire religion tao taoisme yang yin",
  "✝️": "chretien chretienne croix latine religion",
  "☦️": "chretien chretienne croix orthodoxe religion",
  "☪️": "et etoile islam lune musulman musulmane ramadan religion",
  "☮️": "amour and de et love paix peace symbole",
  "🕎": "branches candelabre chandelier hanoucca hanoukka judaisme juif juive menora menorah religion sept",
  "🔯": "branches chance etoile judaisme juif juive",
  "🪯": "deg fateh foi khalsa khanda religion sikh sikhisme tegh",
  "♈": "astrologie belier horoscope zodiaque",
  "♉": "astrologie horoscope taureau zodiaque",
  "♊": "astrologie gemeaux horoscope zodiaque",
  "♋": "astrologie cancer crabe horoscope zodiaque",
  "♌": "astrologie horoscope lion zodiaque",
  "♍": "astrologie horoscope vierge zodiaque",
  "♎": "astrologie balance horoscope justice zodiaque",
  "♏": "astrologie horoscope scorpion zodiaque",
  "♐": "astrologie horoscope sagittaire zodiaque",
  "♑": "astrologie capricorne chevre horoscope zodiaque",
  "♒": "astrologie eau horoscope verseau zodiaque",
  "♓": "astrologie horoscope poissons zodiaque",
  "⛎": "ophiuchus serpent serpentaire zodiaque",
  "🔀": "aleatoire bouton croisees fleche fleches lecture",
  "🔁": "aiguilles bouton cercle des d’une en fleche fleches horaire montre repeter repetition sens",
  "🔂": "aiguilles avec bouton cercle de des d’une en fleche fleches fois horaire la montre n°1 piste repeter repetition sens une",
  "▶️": "bouton droite fleche lecture lire triangle",
  "⏩": "avance bouton double fleche rapide",
  "⏭️": "bouton double fleche piste scene suivant suivante triangle",
  "⏯️": "bouton fleche lecture lecture/pause pause triangle",
  "◀️": "bouton fleche gauche retour triangle",
  "⏪": "bouton double fleche rapide retour",
  "⏮️": "bouton fleche piste precedent precedente scene triangle",
  "🔼": "bouton fleche haut petit triangle",
  "⏫": "double fleche haut le rapide vers",
  "🔽": "bas bouton fleche petit triangle",
  "⏬": "bas double fleche le rapide vers",
  "⏸️": "bouton pause",
  "⏹️": "bouton carre stop",
  "⏺️": "blanc bouton cercle enregistrement enregistrer point",
  "⏏️": "bouton ejecter",
  "🎦": "camera cinema film",
  "🔅": "brillance faible lumiere luminosite soleil",
  "🔆": "brillance elevee lumiere luminosite soleil",
  "📶": "barres communication couverture de portable reception reseau telephone",
  "🛜": "connexion debit fil haut hotspot internet ordinateur reseau routeur sans smartphone wi-fi wifi wlan",
  "📳": "communication mode portable telephone vibreur",
  "📴": "eteindre eteint portable telephone",
  "♀️": "de femme la symbole",
  "♂️": "de homme l’homme symbole",
  "⚧️": "communaute de la symbole transgenre",
  "✖️": "annuler croix multiplication multiplier noire non signe",
  "➕": "addition ajouter arithmetique mathematiques plus signe somme",
  "➖": "arithmetique mathematiques moins signe soustraction soustraire",
  "➗": "algebre diviser division math mathematique mathematiques signe",
  "🟰": "egal egalite gras mathematiques reponse signe",
  "♾️": "eternite illimite infini universel",
  "‼️": "!! double d’exclamation exclamation point ponctuation surprise",
  "⁉️": "!? d’exclamation d’interrogation et exclamation interrogation point points ponctuation question surprise",
  "❓": "d’interrogation interrogation point ponctuation question rouge",
  "❔": "blanc d’interrogation interrogation point ponctuation question",
  "❕": "blanc d’exclamation exclamation point ponctuation surprise",
  "❗": "d’exclamation exclamation point ponctuation rouge",
  "💱": "argent banque change conversion de devise",
  "💲": "argent devise dollar especes payer symbole",
  "⚕️": "caducee docteur esculape medecine personnel",
  "♻️": "recyclage symbole",
  "⚜️": "blason de fleur francaise lis lys reine roi royaute",
  "🔱": "ancre bateau fourche mer poseidon trident",
  "📛": "badge nom nominatif",
  "🔰": "chevron de debutant et japonais jaune symbole vert",
  "⭕": "anneau cercle gros rouge",
  "✅": "blanche bouton carre coche marque ok oui selection termine voila",
  "☑️": "bouton carre case coche cochee ok oui selection termine voila",
  "✔️": "coche noire ok oui selection termine voila",
  "❌": "annuler croix multiplication multiplier rouge",
  "❎": "bouton croix multiplier vert",
  "➰": "boucle bouclette",
  "➿": "boucle double",
  "✳️": "asterique asterisque branches etoile huit",
  "✴️": "asterisque branches etoile huit",
  "❇️": "briller eclat etinceler etincelle scintiller",
  "©️": "copyright droits d’auteur intellectuelle propriete symbole",
  "®️": "commerciale deposee marque",
  "™️": "commerciale deposee marque tm",
  "🔠": "abcd alphabet en latin latines lettres majuscules saisie",
  "🔡": "abcd alphabet de latin latines lettre lettres minuscules saisie",
  "🔢": "1234 chiffres de saisie",
  "🔣": "de saisie symboles",
  "🔤": "abc alphabet de latin lettres saisie",
  "🅰️": "groupe sanguin",
  "🆎": "ab groupe sanguin",
  "🅱️": "groupe sanguin",
  "🆑": "bouton cl effacer icone",
  "🆒": "bouton cool icone",
  "🆓": "bouton gratuit icone",
  "🆔": "bouton icone id identifiant",
  "🆕": "bouton icone nouveau nouveaute",
  "🆖": "bien bouton interdit mauvais ng pas",
  "🅾️": "groupe sanguin",
  "🆗": "bouton icone ok",
  "🅿️": "bouton panneau parking",
  "🆘": "au bouton icone l’aide secours sos",
  "🆙": "bouton haut icone le nouveau nouveaute up vers",
  "🆚": "bouton contre icone versus vs",
  "🈁": "bouton en ici ideogramme japonais katakana",
  "🈂️": "bouton de en frais ideogramme japonais katakana service",
  "🈷️": "bouton en ideogramme japonais mensuel montant",
  "🈶": "bouton en gratuit ideogramme japonais pas payant",
  "🈯": "bouton en ideogramme japonais reserve",
  "🉐": "affaire avantage bonne bouton en ideogramme japonais",
  "🈹": "bouton en ideogramme japonais rabais reduction",
  "🈚": "bouton en gratuit ideogramme japonais",
  "🈲": "bouton en ideogramme interdit japonais",
  "🉑": "acceptable accepter bouton en ideogramme japonais",
  "🈸": "application appliquer bouton en ideogramme japonais",
  "🈴": "bouton de en ideogramme japonais note passage pour reussir",
  "🈳": "bouton chambres disponibles en ideogramme japonais vide",
  "🈺": "affaires bouton en ideogramme japonais ouvert pour",
  "🈵": "bouton complet en ideogramme japonais plenitude",
  "🔴": "cercle disque forme geometrie geometrique rond rouge",
  "🟠": "cercle disque forme geometrie geometrique orange rond",
  "🟡": "cercle disque forme geometrie geometrique jaune rond",
  "🟢": "cercle disque forme geometrie geometrique rond vert",
  "🔵": "bleu cercle disque forme geometrie geometrique rond",
  "🟣": "cercle disque forme geometrie geometrique rond violet",
  "🟤": "brun cercle disque forme geometrie geometrique marron rond",
  "⚫": "cercle disque forme geometrie geometrique noir rond",
  "⚪": "blanc cercle disque forme geometrie geometrique rond",
  "🟥": "carre forme geometrie geometrique rouge",
  "🟧": "carre forme geometrie geometrique orange",
  "🟨": "carre forme geometrie geometrique jaune",
  "🟩": "carre forme geometrie geometrique vert",
  "🟦": "bleu carre forme geometrie geometrique",
  "🟪": "carre forme geometrie geometrique violet",
  "🟫": "brun carre forme geometrie geometrique marron",
  "⬛": "carre forme geometrie geometrique grand noir",
  "⬜": "blanc carre forme geometrie grand",
  "◼️": "carre forme geometrie geometrique moyen noir",
  "◻️": "blanc carre forme geometrie geometrique moyen",
  "◾": "carre forme geometrie moyen noir petit",
  "◽": "blanc carre forme geometrie moyen petit",
  "▪️": "carre forme geometrie geometrique noir petit",
  "▫️": "blanc carre forme geometrie geometrique petit",
  "🔶": "forme geometrie geometrique grand losange orange",
  "🔷": "bleu forme geometrie geometrique grand losange orange",
  "🔸": "forme geometrie geometrique losange orange petit",
  "🔹": "bleu forme geometrie geometrique losange petit",
  "🔺": "fleche forme geometrie geometrique haut le pointant pointe rouge triangle vers",
  "🔻": "bas fleche forme geometrie le pointant pointe rouge triangle vers",
  "💠": "avec bande bd dessin dessinee diamant geometrie geometrique interieur point un",
  "🔘": "bouton forme geometrie geometrique radio rond",
  "🔳": "blanc bouton carre forme geometrie",
  "🔲": "bouton carre forme geometrie noir",
  "🏳️": "au blanc drapeau flotte qui vent",
  "🏁": "automobile course damier drapeau d’arrivee formule ligne sport vainqueur",
  "🚩": "drapeau fanion golf rouge triangulaire",
  "🎌": "croises drapeaux japonais",
  "🏴": "au drapeau flotte noir qui vent",
  "🏳️‍🌈": "arc-en-ciel drapeau lgbt",
  "🏳️‍⚧️": "blanc bleu clair drapeau rose transgenre",
  "🏴‍☠️": "de drapeau pillage piller pirate tresor",
};
